src/unit-tests/oscore-test/ut_oscore_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfile-test/ut_osfile_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.c
Fixes #15 
- Remove unused variable
- Add local function prototype where missing
- Qualify all pointers to string literals as `const`
Rebuild OSAL per default configuration with unit tests enabled
Re-ran all unit tests and confirm passage
No warnings generated when using `-Wall -Werror -std=c99 -pedantic -Wwrite-strings -Wstrict-prototypes'
Ubuntu 18.04 (64-bit)
=> Fix #15 unit test warnings

src/os/shared/osapi-time.c, src/unit-test-coverage/shared/src/coveragetest-time.c
Update OS_TimerSet to return OS_ERROR when both parameters are zero.
1. Build steps 
2. Modify sample app to make OS_TimerSet API call with both parameters as zero
3. Verify return. 
- API Change: OS_TimerSet
- Hardware
- OS: Ubuntu 18.04.03
- cFS 6.7, GroundSystem 2.1.0, 
**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted
=> Fix #11, Update OS_TimerSet to return OS_ERROR 

src/os/shared/osapi-timebase.c
Fix issue #274, avoids timer callback deadlock if actual tick_time is consistently bigger than the configured iinterval_time.
Modify `timer-test` to choose an interval that is not a multiple of the system clock tick, such that it will be rounded up to the next tick by the implementation.
Verify that evenually, two callbacks are generated in a single time tick, such that the long-term average of callbacks over time is consistent with the configured interval_time.
Confirm that callbacks continue normally until the application is stopped, as expected.
Callbacks no longer cease once the "overrun" condition occurs (callbacks behind by >=1 full interval time)
Confirm consistent behavior on POSIX, RTEMS, and …
=> Fix #274: Avoid possible deadlock of timer callback

src/os/vxworks/osapi.c
Fixes #269, Corrects the error check after taskSpawn in the vxworks implementation.
The test for failure of taskSpawn should be for the value of
ERROR, not 0, per the VxWorks API documentation.
Found when implementing the unit test improvements in #230.
This issue is generally only reproducible in UT where taskSpawn
can be made to fail.  In normal FSW/runtime use, the taskSpawn
call is not likely to fail, and this issue cannot be seen.
Build OSAL coverage tests (see #268) and confirm passage of all tests.
All unit tests pass, fixes a failure in one test due to this incorrect error test.
Ubuntu 18.04.2 LTS 64-bit
=> Correct error checking for taskSpawn

src/os/posix/ostimer.c, src/os/rtems/ostimer.c, src/os/vxworks/ostimer.c, src/tests/timer-test/timer-test.c
Fixes issue #271, corrects the time intervals returned by the sigwait() routines for all three operating systems (POSIX, RTEMS, VxWorks).
Testing is focused on the operation of the `timer-test` example program and variations thereof.
Verified that all callbacks from all timers correlate with the configured "start_time" and "interval_time" parameters passed to the OS_TimerSet() configuration.
Verified CFE still boots and runs OK. (stops FLYWHEEL as normal based on 1Hz tick)
No changes to applications/CFE.
The `timer-test` example program now runs and passes consistently on all platforms.
Ubuntu 18.04.2 LTS 64 bit (simulation)
RTEMS 4.11 pc686 BSP running in QEMU
MPC750 VxWorks 6.9 …
=> Fix #271: Correct interval time computations

src/os/rtems/osfilesys.c
Fixes issue #273
Just adds a typecast to avoid the warning
Build code on i686-rtems4.11 platform, with -Wall -Werror and OS_DEBUG_PRINTF option enabled.
Observe no more warning about the format mismatch.
Ubuntu 18.04.2 LTS 64 bit (build host) using i686-rtems4.11 cross toolchain
=> Fix #273: Correct format code in debug message

src/tests/sem-speed-test/sem-speed-test.c
Fix issue #272
Use a nonzero stack size for this test.
Build and execute "sem-speed-test" on the MPC750 VxWorks platform.
Test now runs and passes reliably with no odd/inconsistent behaviors
MPC750 VxWorks 6.9
=> Fix #272: use 4K stack for sem-speed-test tasks

src/unit-tests/oscore-test/ut_oscore_binsem_test.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c, src/unit-tests/oscore-test/ut_oscore_exception_test.c, src/unit-tests/oscore-test/ut_oscore_interrupt_test.c, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/oscore-test/ut_oscore_mutex_test.c, src/unit-tests/oscore-test/ut_oscore_queue_test.c, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c, src/unit-tests/osprintf-test/ut_osprintf_misc.c, src/unit-tests/osprintf-test/ut_osprintf_offset.c, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Resolve cppcheck warning for unit-tests.
Did not compiled unit test. 
1. cppcheck -force --inline-suppr . 2>cppwarning
2. Verify warning is gone. 
- Hardware
- Ubuntu 18.04
- OSAL 1.4.2a, cppcheck 1.82
**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted
=> Fix #286, fix cppcheck warning for unit-test

src/os/inc/osapi-os-core.h, src/os/inc/osapi-os-filesys.h
Fix #280, fix misc. doxygen warning
1. make users guide
2. verify warning is gone
- Hardware
- Ubuntu 18.04
- doxygen 1.8.13, rc-6.7.0
=> Fix #280, fix misc. doxygen warning

src/os/posix/osapi.c, src/os/shared/osapi-time.c, src/unit-test-coverage/shared/src/coveragetest-time.c, src/unit-test-coverage/shared/src/coveragetest-timebase.c, src/unit-test-coverage/ut-stubs/src/libc-stdio-stubs.c
Replace use of `1<<31` and `INT_MAX` with `UINT32_MAX/2` which should
squelch the cppcheck warnings about the left shift as well as being
more correct (the values in question are uint32's, not int's).
Also address two false positives about a return value being unassigned,
by simply initializing the value to be 0.
Fixes issue #287
Build coverage test and ensure all tests passing and line coverage is unaffected
Build and run CFE and confirm no effect.
Ran cppcheck and confirmed that warnings are gone.
No impact to behavior.
Ubuntu 18.04 LTS, 64 bit.
**Community contributors**
You must attach a signed CLA (required for …
=> Fix #287: cppcheck warnings

src/os/inc/osapi-os-core.h, src/os/inc/osapi-os-filesys.h, src/os/posix/osapi.c, src/os/shared/osapi-time.c, src/unit-test-coverage/shared/src/coveragetest-time.c, src/unit-test-coverage/shared/src/coveragetest-timebase.c, src/unit-test-coverage/ut-stubs/src/libc-stdio-stubs.c, src/unit-tests/oscore-test/ut_oscore_binsem_test.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c, src/unit-tests/oscore-test/ut_oscore_exception_test.c, src/unit-tests/oscore-test/ut_oscore_interrupt_test.c, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/oscore-test/ut_oscore_mutex_test.c, src/unit-tests/oscore-test/ut_oscore_queue_test.c, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c, src/unit-tests/osprintf-test/ut_osprintf_misc.c, src/unit-tests/osprintf-test/ut_osprintf_offset.c, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Fixes #280, fixes #286, fixes #287
1. Checked out bundle with ic-20191115 branches 
1. make ENABLE_UNIT_TESTS=TRUE SIMULATION=native prep
1. make
1. make install
1. make test
Built without warnings, all tests passed except osal_timer_UT (nominal result on linux)
executed cfe, successful startup with no warnings
Confirmed passed CI (with cppcheck enforced!)
No functional changes, all doxygen/cppcheck warning/error cleanup
- cFS dev server
- OS: Ubuntu 16.04
- Versions: bundle ic-20191115 branch
None
=> Integration Candidate 20191115

src/os/inc/osapi-os-net.h, src/os/portable/os-impl-bsd-sockets.c
Fix #295 
Add a union wrapper for the abstract data field such that it will be aligned for 32 bit integer values and/or pointers, whichever is greater.
This removes cast alignment warnings in this code with compiling on CPU architectures with strict alignment requirements.
Build code with full warnings (including -Wcast-align) on both native (x86-64) and MIPS32
Execute CFE on native (x86-64) (with CI_LAB/TO_LAB that use OSAL-provided socket abstraction), confirm no changes in behavior.
No compiler warning.  No changes to runtime behavior.
Linux MIPS 32 bit (build)
Ubuntu 18.04 LTS, 64 bit (build + run)
**Community …
=> Add alignment wrapper to OS_SockAddr_t

src/os/inc/osapi-os-core.h, src/os/portable/os-impl-posix-dl.c, src/os/posix/osapi.c, src/os/rtems/osapi.c, src/os/rtems/osloader.c, src/os/shared/os-impl.h, src/os/shared/osapi-fpu.c, src/os/vxworks/osapi.c, src/os/vxworks/osloader.c, src/os/vxworks/ostimer.c, src/unit-test-coverage/shared/src/coveragetest-dir.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-test-coverage/shared/src/coveragetest-time.c, src/unit-test-coverage/ut-stubs/src/osapi-base-impl-stubs.c, src/unit-test-coverage/ut-stubs/src/osapi-loader-impl-stubs.c, src/unit-test-coverage/vxworks/modules/inc/ut-osloader.h, src/unit-test-coverage/vxworks/modules/src/ut-osloader.c, src/unit-test-coverage/vxworks/src/coveragetest-osfilesys.c, src/ut-stubs/osapi-utstub-fpu.c
Fix #298
Fix warnings that are triggered by compiling the OSAL coverage unit test with strict settings.
- The `OS_FPUExcAttachHandler()` function needs to be prototyped as accepting a function pointer (not `void*`)
- Const-Correctness on `OS_ModuleLoad_Impl()`
- Use `void*` instead of `char*` for buffer pointer as the specific type is not known
- Cast the function passed into `taskSpawn()` on VxWorks
Build code on all three supported OS's (POSIX, RTEMS, VxWorks) with full warnings and ENABLE_UNIT_TESTS=TRUE
Execute all unit tests and confirm passage
Execute cFE and confirm normal operation
None.
- Ubuntu 18.04 LTS, 64-bit (native)
- VxWorks 6.9 / MCP750 (GSFC build machine)
- RTEMS …
=> Fix minor warnings in OSAL code

src/ut-stubs/osapi-utstub-file.c, src/ut-stubs/osapi-utstub-mutex.c, src/ut-stubs/osapi-utstub-queue.c, src/ut-stubs/osapi-utstub-task.c, src/ut-stubs/utstub-helpers.c
resolve cppcheck warning. 
1. make ENABLE_UNIT_TESTS=TRUE SIMULATION=native prep
2. make
3. make install
4. make test
5. Verify passing unit-test
6. cppcheck --force --inline-suppr --std=c99 --language=c --error-exitcode=1 enable=warning,performance,portability,style --suppress=variableScope --inconclusive osal/src 2>osal.txt
- Hardware
- osal 5.03
=> issue #305, Resolve cppcheck warning ut_stubs

src/os/portable/os-impl-posix-dl.c, src/os/posix/os-posix.h, src/os/posix/osapi.c, src/os/rtems/osloader.c
Resolve cppcheck for os dir.  Possible cppcheck bug for structure member - suppress. 
1. make prep, make, make install
2. run 
- Hardware
- Ubuntu 18.04
-  CFE 6.6
=> issue #308, Resolve cpp warning in os dir.

src/os/posix/osapi.c, src/os/rtems/osapi.c, src/os/shared/osapi-fpu.c
Fix #316
- Ensure the FPU functions that are actually not implemented in RTEMS/POSIX all return OS_ERR_NOT_IMPLEMENTED, not OS_SUCCESS.
- The RTEMS IntEnable/Disable API should not be a duplicate of the IntLock/Unlock API, as the semantics are slightly different.
The Enable/Disable API should return OS_ERR_NOT_IMPLEMENTED.
- The OS_FPUExcGetMask API should confirm that the output buffer is not NULL.
Sanity check on basic CFE operation on native/simulation build - no changes to FSW behavior.
Modified APIs are exercised in the OSAL unit tests.  Unit tests executed on RTEMS, POSIX (native), and VxWorks in conjunction with changeset for #313.
No change to FSW.
Unit tests related to these particular API calls now …
=> Exception/Interrupt API updates

src/unit-test-coverage/ut-stubs/src/posix-time-stubs.c, src/unit-test-coverage/vxworks/src/coveragetest-ostimer.c
Fix #321
This is related to the change for #271, where the return value of this function depends on the configured timer interval.  The coverage test case for this was not updated in the original change.
Build and execute OSAL coverage tests
Test case now passes, as:
```
[BEGIN] 03 OS_VxWorks_SigWait
[ PASS] 03.001 coveragetest-ostimer.c:166 - Osapi_Internal_CallSigWaitFunc(0) (1111111) == 1111111 (1111111)
[ PASS] 03.002 coveragetest-ostimer.c:168 - Osapi_Internal_CallSigWaitFunc(0) (2222222) == 2222222 (2222222)
[ PASS] 03.003 coveragetest-ostimer.c:170 - Osapi_Internal_CallSigWaitFunc(0) (2222222) == 2222222 (2222222)
[  END] 03 OS_VxWorks_SigWait   TOTAL::3     PASS::3     FAIL::0      MIR::0      TSF::0 …
```
=> Update OS_VxWorks_SigWait test case

src/tests/sem-speed-test/sem-speed-test.c
Fix #323
1. Add a hard limit to the execution (work) counter for the sem-speed-test worker threads.  With this they will self-exit eventually even if the root task never gets CPU time to stop them.
2. Set the priority of the worker tasks to be logically lower, so it is less likely to preempt the main task.
Note that the logical priority is inverted from the numeric value.
Execute unit tests on RTEMS and native (posix/x86-64) and confirm successful operation of the sem-speed-test on both platforms.
Example output from running in RTEMS:
```
[BEGIN] 01 SemSpeedTest
[ PASS] 01.001 sem-speed-test.c:163 - Sem 1 create Id=196609 Rc=0
[ PASS] 01.002 sem-speed-test.c:165 - Sem 2 create Id=196610 Rc=0
[ PASS] 01.003 sem-speed-test.c:171 - Task 1 …
```
=> Avoid infinite sem-speed-test

src/os/posix/ostimer.c, src/unit-tests/ostimer-test/ut_ostimer_test.c
Fix #335 
On POSIX, call sigtimedwait() on the selected RT signal as part of the set up for the timebase.  This ensures that if the signal is already pending, it will be cleared.
This also simplifies the timer callback routine in the UT code, cleaning up some unnecessary extra logic.
Build with ENABLE_UNIT_TESTS=TRUE and execute `osal_timer_UT` in a repeated loop.
Prior to this fix, it would typically fail after about 10-20 iterations, sometimes fewer.
After this fix, it does not fail (100+ iterations, no failures).
Confirmed normal operation of CFE core (no change).
Fixes occasional failures in the nominal timer test.
No change to FSW code
Ubuntu 18.04 LTS, 64 Bit
**Additional …
=> Clear pending signal when configuring timer

src/os/posix/os-posix.h, src/os/shared/osapi-idmap.c, src/os/shared/osapi-sockets.c, src/os/shared/osapi-time.c
fix lgtm warning. 
1. Build against dummy repo using lgtm.
2. Verify warning is fixed
3. Cppcheck.
4. Verify no warning 
5. Build 
6. Verify still build.
- Hardware
- Ubuntu 18.04
-  CFE 6.6
Anh Van, NASA Goddard.
=> fix #328, lgtm warning

src/os/posix/osapi.c
This PR fixes #337. The exact change has been recommended by @jphickey.
Currently, I cannot test this on Linux only on macOS. As reported in the issue, I confirm that that the issue gets fixed with this change applied. Also, the bug has been confirmed by @jphickey and the changeset is created from his recommendation.
See related issue: #337.
Running osal-core-test tests (BSEM tests)
OS: macOS Mojave 10.14.6 (18G87)
Versions: master branch as of 155e9ebcd6d1930890231a44237e6883d229d22c.
Stanislav Pankevich, personal
The signed individual CLA has been sent to the email specified in the CLA document.
=> Fix #337, fix memory corruption produced by misplaced memset()

README.md, src/os/inc/osapi-version.h, src/os/posix/osapi.c
Describe the contribution
Fix #338  
Testing performed
Current CI passes
Test 4 in Enhanced CI in https://github.com/nasa/cFS/pull/40
Expected behavior changes
#338 - Fixes memset bug in `src/os/posix/osapi.c `
System(s) tested on
CI: Ubuntu 18.04
Additional context
N/A
Third party code
N/A
Contributor Info - All information REQUIRED for consideration of pull request
Gerardo E. Cruz-Ortiz - NASA/GSFC
=> IC - 20200226

src/os/rtems/osloader.c
When OS_INCLUDE_MODULE_LOADER is not defined, the function header does not
match the definition. This issue was introduced in PR #21 .
Longer term: is there a continuous integration strategy to avoid this sort of situation happening in the future? 
Build with module loader disabled with cFS master distribution.
None
- PC, Ubuntu 19.04
Andrei-Costin Zisu of Planetary Transportation Systems GmbH (Berlin, Germany). Company-wide CLA is in the process of being signed and should be available soon.
=> Fix #357: Make parameter const

src/os/rtems/osloader.c
Integration Candidate 20200304
Fixes #357 
See PR #356 for details
CI, Ubuntu-Bionic
None
See PR #356 
Andrei-Costin Zisu - Planetary Transportation Systems GmbH (Berlin, Germany). 
Gerardo E. Cruz-Ortiz - NASA/GSFC
=> IC 20200304

src/os/shared/osapi-sockets.c
Fixes #349, note that this does *not* include unit tests. There don't seem to be any unit tests for the OSAL networking code. We should discuss at the CCB.
Tested with the TCP version of SBN, without the fix it fails on the Accept() call, with the fix, SBN nodes connect and traffic flows as expected.
OS_SocketAccept() should work to accept new incoming TCP connections.
64-bit Debian 9 VM.
None
Christopher.D.Knight@nasa.gov
=> Fix #349, OS_SocketAccept() fix

README.md, src/os/inc/osapi-version.h, src/os/shared/osapi-sockets.c
Fixes #349
PR #372 
[Bundle CI](https://travis-ci.com/github/nasa/cfs/builds/158274344)
OS_SocketAccept() should work to accept new incoming TCP connections.
Bundle CI - Ubuntu: Bionic
Christopher. D. Knight - NASA/ARC
Gerardo E. Cruz-Ortiz - NASA/GSFC
=> Integration Candidate 2020-03-25

src/tests/bin-sem-flush-test/bin-sem-flush-test.c
Describe the contribution
Fixes #347, replace task_1_work with correct variable names
Testing performed
Ran unit tests
Expected behavior changes
The correct variable values will now be displayed when the test is executed.
System(s) tested on
Oracle VM VirtualBox
OS: ubuntu-19.10
Versions: cFE 6.7.10.0, OSAL 5.0.8.0, PSP 1.4.7.0,
Contributor Info
Dan Knutsen
NASA/Goddard
=> Fix #347, replaces task_1_work with correct variable names

.travis.yml
Fix #389 
Resolve CI config warnings
1. CI (CI config change only)
No more config warnings reported by Travis-CI
- Hardware: CI
- Versions: master w/ this commit
None
None
=> Fix #389, Resolve CI config warnings

src/os/posix/osapi.c
Fixes #232 PTHREAD_STACK_MIN typo. I could have changed the number to 8192 but I thought (8*1024) was more true to where the number comes from. Let me know if this is not inline with NASA code style preferences.
1. Build steps: built with cmake:
`cmake -DOSAL_SYSTEM_OSTYPE=posix -DOSAL_SYSTEM_BSPTYPE=pc-linux -DENABLE_UNIT_TESTS=TRUE -DOSAL_INCLUDEDIR=/home/david/projects/config -DCFE_SYSTEM_PSPNAME=whyohwhy /home/david/projects/osal`
1. Ran all tests and unit tests.
Note that osloader module test nominal 7 failed (ut_osloader_module_test.c:242) but it failed no matter whether my changes were implemented or not. I assume it's a quirk of my system/environment.
- no impact …
=> Fix #232, pthread stack min typo

src/os/inc/osapi-os-core.h
Fixes #407 by removing a duplicate reference the doxygen warned about
1. Edited file in which error occurred
2. Rebuilt documentation using `make doc`
3. Observed no warning generated
4. Viewed relevant documentation page to verify correctness
Leor Bleier NASA-GSFC
=> Fix #407, Resolve doxygen warnings for main doc

src/bsp/mcp750-vxworks/config/osconfig.h, src/bsp/pc-linux/config/osconfig.h, src/bsp/pc-rtems/config/osconfig.h, src/os/inc/osapi-os-core.h, src/os/inc/osapi-os-net.h, src/os/inc/osapi-os-timer.h, src/os/inc/osapi.h, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Describe the contribution
Fixes #88, Add test for name too long and update comments.
Coverage test added to OS_TimerCreate for OS_ERR_NAME_TOO_LONG.
Updated comments related to sizing includes null terminator for:
OS_MAX_API_NAME, OS_MAX_PATH_LEN, OS_BUFFER_SIZE
Testing performed
Ran unit tests.
System(s) tested on
Oracle VM VirtualBox
OS: ubuntu-19.10
Versions: cFE 6.7.11.0, OSAL 5.0.9.0, PSP 1.4.7.0
Contributor Info
Dan Knutsen
NASA/Goddard
=> Fix #88, Add test for name too long and update comments 

src/os/inc/osapi-os-filesys.h, src/tests/file-api-test/file-api-test.c
Fix #368
Deprecates the define and updates the reference in unit test
CI - https://travis-ci.com/github/skliper/cFS/builds/159834459
None
- CI, master bundle w/ this branch
None
None
=> Fix #368, Deprecate os_fs_err_name_t

README.md
Fix413: Added reference to osal user's guide from ReadMe
1. Went to GitHub to verify that that link added worked properly
**Expected Behavior Changes**
None
- GNOME VM
- Versions: OSAL 5.0.11.0
**Contributor **
Yasir Khan
NASA GSFC
=> Fix #413, Add reference to osal user's guide from ReadMe

CMakeLists.txt, src/bsp/mcp750-vxworks/CMakeLists.txt, src/bsp/pc-linux/CMakeLists.txt, src/bsp/pc-rtems/CMakeLists.txt
Simplify user configuration by inferring the `OSAL_SYSTEM_OSTYPE` from the `OSAL_SYSTEM_BSPTYPE` if the former is not set.  This means the user does not have to explicitly set both of these configuration options.
In the event they are _both_ explicitly set (as is done in the current configurations) but refer to an invalid/unexpected combination of OS+BSP, this adds a warning message to the CMake setup (make prep) stage, as this is likely a mis-configuration that deserves attention, but there could be valid reasons for doing this during development.
Fixes #432 
Build OSAL for various platform combos (native, x86-linux cross, i686-rtems4.11 cross).  Confirm successful build.  
No FSW affected, only build …
=> Fix #432, Infer OSAL_SYSTEM_OSTYPE from OSAL_SYSTEM_BSPTYPE

src/unit-test-coverage/shared/src/coveragetest-idmap.c
Fix #425 Test_OS_ConvertToArrayIndex: tautological assertion
Unit test Test_OS_ConvertToArrayIndex implements the following assertion:
osal/src/unit-test-coverage/shared/src/coveragetest-idmap.c
Lines 610 to 611 in 7d9c4c8
UtAssert_True(local_idx1 == local_idx1, "local_idx1 (%lu) == local_idx2 (%lu)", 
(unsigned long)local_idx1, (unsigned long)local_idx2); 
This is a tautological assertion as it compares local_idx1 with itself.  
Update:
local_idx1 is now compared with local_idx2:
UtAssert_True(local_idx1 == local_idx2, "local_idx1 (%lu) == local_idx2 (%lu)",
(unsigned long)local_idx1, (unsigned long)local_idx2);
**System(s) tested …
=> Fix #425, Correct Test_OS_ConvertToArrayIndex assertion typo

.travis.yml
Fix #346, Adds library build, functional, and coverage test to CI
1. CI from fork - https://travis-ci.com/github/skliper/osal/builds/157641624
Just adds tests to CI
- Hardware: AMD
- Versions: bundle + warning fix from previous pull request + this change
None
None
=> Fix #346, Adds library build, functional, and coverage test to CI

src/tests/osal-core-test/osal-core-test.c
Loops the parent OS_TaskDelay until child task exits before testing OS_TaskDelete.  Avoids the test depending on system loading/performance with single delay approach.
Fix #424 
1. Standard build, ran `osal-core-test -d` and observed Loop count of 1 (I've never experienced the failure, which if avoided would have a loop count > 1)
Consistent osal-core-test execution status
- Hardware: cFS Dev Server 3
- Versions: Bundle + this commit
Issue seen on dev server 4 and Mac OS
None
=> Fix #424, Add looping wait for self exiting task

src/unit-tests/osloader-test/CMakeLists.txt
Fixes #430.
Running `osal_loader_UT` on macOS as described in the linked issue.
Without this patch, the MODULE* files are not generated in the build folder.
After this patch is applied, the module files are generated when the `osal_loader_UT` test is built and run:
```
$ find . | grep MODULE.*dy
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE31.dylib
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE5.dylib
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE28.dylib
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE7.dylib
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE3.dylib
./cmake-build-debug/unit-tests/osloader-test/eeprom1/MODULE6.dylib …
```
=> unit-tests/osloader-test: make modules always be built for the test

src/bsp/mcp750-vxworks/config/osconfig.h, src/bsp/pc-linux/config/osconfig.h, src/bsp/pc-rtems/config/osconfig.h, src/os/inc/osapi-os-filesys.h, src/os/portable/os-impl-posix-dirs.c, src/os/portable/os-impl-posix-files.c, src/os/portable/os-impl-posix-io.c, src/os/posix/osfilesys.c, src/os/rtems/osfileapi.c, src/os/rtems/osfilesys.c, src/os/rtems/osshell.c, src/os/shared/osapi-dir.c, src/os/shared/osapi-file.c, src/os/shared/osapi-filesys.c, src/os/vxworks/osfileapi.c, src/os/vxworks/osfilesys.c, src/os/vxworks/osshell.c, src/tests/file-api-test/file-api-test.c, src/unit-test-coverage/portable/coveragetest-posixfile.c, src/unit-test-coverage/portable/coveragetest-posixio.c, src/unit-test-coverage/shared/src/coveragetest-file.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/vxworks/src/coveragetest-osfilesys.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfile-test/ut_osfile_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c, src/ut-stubs/osapi-utstub-filesys.c
Changes FileName in os_dirent_t from OS_MAX_PATH_LEN to OS_MAX_FILE_NAME,
and moves OS_check_name_length into OS_TranslatePath so it is
consistantly applied everywhere. Also fixes the length checks in
OS_check_name_length to account for terminating null.
Unit tests updated to match new directory name limit.
Fix #344
1. CI - https://travis-ci.com/github/skliper/cFS/builds/160789041
Individual directory names now limited to OS_MAX_FILE_NAME
- Hardware: cFS Dev Server 3
- Versions: bundle + this branch
Note it's based on #421 to avoid conflicts and help with IC merge.
None
**Contributor …
=> Fix #344, Consistent directory entry size limit

src/os/inc/osapi-os-core.h, src/os/posix/src/os-impl-tasks.c, src/os/rtems/src/os-impl-tasks.c, src/os/shared/inc/os-shared-task.h, src/os/shared/src/osapi-task.c, src/os/vxworks/src/os-impl-tasks.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-test-coverage/ut-stubs/src/osapi-task-impl-stubs.c, src/unit-test-coverage/vxworks/src/coveragetest-tasks.c, src/ut-stubs/osapi-utstub-task.c
The OS_task_prop_t had contained an `OStask_id` field which was used for reverse-mapping the OSAL task ID during exception processing by CFE.  Unfortunately this was a uint32 and not compatible with any OS which used task identifiers that were not convertible to such a value (e.g. `pthread_t`, or 64-bit pointers, etc).
Deprecate the old field and replace with a new API that performs reverse lookup within OSAL using an abstract pointer and size, so its compatible with any OS task representation object.
Fix #437 
Tested as part of testing exceptions within the scope of PR's nasa/psp#159 and nasa/cfe#653.
Confirm that the newly-added APIs are performing as expected.
New API to reverse lookup an OS-provided …
=> Fix #437, Add new API for obtaining exception task ID

src/os/shared/inc/os-shared-filesys.h, src/os/shared/src/osapi-filesys.c, src/unit-tests/inc/ut_os_support.h
Resize buffers and add explicit termination to string copies.
Avoids warnings on GCC9 with strict settings and optimization enabled.
Fixes #435
Build with default config and gcc 9.3.0 and confirm warnings are gone
Warnings fixed.
Ubuntu 20.04 LTS
Currently a draft because it uses PR #427 as a baseline.  Will mark as non-draft once prerequisite is merged.
Joseph Hickey Vantage Systems, Inc.
=> Fix #435, fix string manipulations to avoid warnings

README.md, src/os/inc/osapi-os-core.h, src/os/inc/osapi-version.h, src/os/posix/src/os-impl-tasks.c, src/os/rtems/src/os-impl-tasks.c, src/os/shared/inc/os-shared-filesys.h, src/os/shared/inc/os-shared-task.h, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-task.c, src/os/vxworks/src/os-impl-tasks.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-test-coverage/ut-stubs/src/osapi-task-impl-stubs.c, src/unit-test-coverage/vxworks/src/coveragetest-tasks.c, src/unit-tests/inc/ut_os_support.h, src/ut-stubs/osapi-utstub-task.c
Fix #437, add new API for obtaining exception task ID
Fix #435, Changes for string ops warnings 
See PRs
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/165726730
PR #441 - Resized buffers and added explicit termination to string copies. No warnings on GCC9 with strict settings and optimization enabled.
PR #446 - New API to reverse lookup an OS-provided thread/task identifier back to an OSAL ID.
Any use of existing OStask_id field within the task property structure is now deprecated.
See PRs
Part of nasa/cfs#83
=> Integration Candidate COMBINED 2020-04-29 and 2020-05-06

src/os/inc/osapi-os-core.h, src/os/shared/src/osapi-queue.c, src/unit-test-coverage/shared/src/coveragetest-queue.c
The `OS_QueueCreate()` function will now sanity check the depth parameter against the configured OS_MAX_QUEUE_DEPTH value.  If it is too large, an error will be returned.  This is a hard limit
and independent of the "permissive" mode.
The OS_MAX_QUEUE_DEPTH should be configured to the largest value that an application may reasonably request.
Fix #235 
Confirm CFE framework starts and operates normally (but see nasa/to_lab#36)
Confirm OSAL unit tests pass
`OS_QueueCreate()` will return an error code if the depth parameter is larger than the configured `OS_MAX_QUEUE_DEPTH`.
Ubuntu 20.04
Joseph Hickey, …
=> Fix #235, add check against OS_MAX_QUEUE_DEPTH

README.md, src/os/inc/osapi-os-core.h, src/os/inc/osapi-version.h, src/os/shared/src/osapi-queue.c, src/unit-test-coverage/shared/src/coveragetest-queue.c
Fix #235
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/167639047
PR #448 - `OS_QueueCreate()` will return an error code if the depth parameter is larger than the configured `OS_MAX_QUEUE_DEPTH`. 
Ubuntu:Bionic
See PRs for detailed test and change information
Part of nasa/cfs#87
=> Integration Candidate 2020-05-13

src/os/shared/inc/os-shared-filesys.h, src/os/shared/src/osapi-filesys.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c
The `device_name` field was using the wrong length, it should be of `OS_FS_DEV_NAME_LEN`
Also correct another length check on the local path name.
Fix #455 
Build and execute unit tests, and sanity check CFE operation.
=> Fix #455, correct length of device_name in filesys

src/os/posix/src/os-impl-idmap.c, src/os/rtems/src/os-impl-idmap.c, src/os/vxworks/src/os-impl-idmap.c
Adds the mutex to protect the timer callback (timecb) resource table.
Fixes #474 
Build and confirm all unit tests pass, CFE runs normally.
Timer callback (timcb) resource types are mutex protected.
Ubuntu 20.04 
=> Fix #474, Add timecb global mutex

src/os/inc/osapi-os-core.h, src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-time.c, src/tests/osal-core-test/osal-core-test.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/ut-stubs/osapi-utstub-idmap.c
Implement `OS_GetResourceName()` and `OS_ForEachObjectOfType()`, which are new functions that allow for additional query capabilities.   `OS_ObjectIdToArrayIndex()` modified to accept `OS_OBJECT_TYPE_UNDEFINED` as the first parameter, to allow it to work with any object type, not just objects for which a specific type is expected/known.
Also adds unit test (functional + coverage)  for `OS_ForEachObjectByType` and `OS_GetResourceName`
Fixes #293
Run all unit tests, sanity check CFE and confirm normal operation
No impact to _current_ behavior as the FSW does not currently use any of these new APIs.  Existing APIs are unchanged.
Ubuntu 20.04
Querying objects by …
=> Fix #293, Expand API for object queries

CMakeLists.txt
If the "OSAL_EXT_SOURCE_DIR" cache variable is set, this location will be checked first for a BSP/OS implementation layer.  This can point to an out-of-tree implementation layer if necessary.
Fixes #450
Configure a test project to use a BSP provided in the external source dir, and confirm that it builds correctly and sanity check result (unit tests, CFE runs normally).
No impact to behavior unless user requires a BSP/OS implementation which is not part of the included set.
Ubuntu 20.04
It is discouraged from actually doing this as there is no attempt at API stability at the low level implementation layer.
The actual location of the implementation layer being …
=> Fix #450, add external source directory for OS/BSP

src/os/posix/src/os-impl-binsem.c, src/tests/bin-sem-test/bin-sem-test.c
Corrects issue when a task waiting on a binary semaphore is deleted, it left the mutex in a locked state preventing other tasks from using the mutex.
This has 3 parts:
1. A functional test enhancement to bin-sem-test which replicates the specific conditions for the observed bug to occur.  It deletes the task calling `OS_BinSemTake()` and then attempts to use the semaphore after this.  (without the rest of this change, it fails).
2. Employ a pthread "cleanup handler" to handle the situation where a task is canceled during the `pthread_cond_wait()` call.  This ensures that the mutex is unlocked as part of the cleanup, so other tasks may continue using the semaphore.  This is the main fix as it directly addresses the root cause of the issue, which is that the …
=> Fix #470, Binary sem task delete issues

src/os/inc/osapi-os-filesys.h, src/os/portable/os-impl-posix-gettime.c
Fixes #447, additional doxygen warnings
1. Corrected the issues referenced in the `warnings.log` file
2. Rebuilt the docs with `make doc`
3. Observed no recurrence of same warnings in `warnings.log`
No doxygen warnings for the affected files
Leor Bleier, NASA GSFC\Code 582
=> Fix #447, Resolve doxygen warnings

src/bsp/pc-rtems/src/bsp_start.c, src/bsp/pc-rtems/src/pcrtems_bsp_internal.h, src/os/rtems/src/os-impl-filesys.c, src/unit-tests/osfile-test/ut_osfile_test.c
Rather than relying on the BSP to preallocate, the ram disk block devices can be created based on request.  This correlates with the way RAM disks are implemented on VxWorks and is
cleaner and more flexible by making it more independent of the BSP.
This allows all the unit tests to work on RTEMS without the needing the BSP to preallocate a ramdisk.
Fixes #459 
Build and run all unit tests, and sanity check CFE operation
Unit tests work on RTEMS without BSP preallocating ramdisks
=> Fix #459, dynamically create RAM disk devices on RTEMS

src/bsp/mcp750-vxworks/src/bsp_start.c, src/bsp/pc-linux/src/bsp_start.c, src/bsp/pc-rtems/src/bsp_start.c, src/bsp/shared/inc/bsp-impl.h, ut_assert/src/utbsp.c
This provides a better method of handling test abort, in a BSP-specific manner.
Fixes #457
Build and execute unit tests on RTEMS platform, and run a test that has a problem causing an abort.  (e.g. `UtAssert_Abort`).
Confirm that in normal (non-batch) mode the system stays alive and allows use of the shell to check the system state.  When using batch mode the system still shuts down (as expected).
No impact to behavior on Linux/VxWorks.
For RTEMS, will not shutdown the kernel if test abort occurs.
=> Fix #457, provide BSP shutdown handler

src/os/rtems/src/os-impl-filesys.c
Map the ENOSYS errno to OS_ERR_NOT_IMPLEMENTED, which is more appropriate than OS_ERROR.
Fixes #454
Build and execute  unit tests on RTEMS 4.11.3
Unit test cases which use OS_statfs and run on an RTEMS IMFS volume (default for the root file system) will be skipped and categorized as "NA" due to OS_ERR_NOT_IMPLEMENTED response, rather than a failure.
=> Fix #454, Better error translation on statvfs()

src/tests/idmap-api-test/idmap-api-test.c
Fix #374, Object Utility API's missing functional test
Created missing functional tests for the OS_IdentifyObject, OS_ConvertToArrayIndex and OS_ForEachObject functions.  
cFS Dev Server
**Contributor Info **
Yasir Khan
NASA GSFC
=> Fix #374, Add Object Utility API functional tests

src/tests/idmap-api-test/idmap-api-test.c
Hotfix #374 object utilitys missing functional api tests
Fixed  OS_ConvertToArrayIndex failing test. Added Copyright.
cFS Dev Server
Yasir Khan
NASA-GSFC
=> Hotfix #374 object utilitys missing functional api tests

src/os/posix/src/os-impl-idmap.c, src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-binsem.c, src/os/shared/src/osapi-countsem.c, src/os/shared/src/osapi-dir.c, src/os/shared/src/osapi-file.c, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-module.c, src/os/shared/src/osapi-mutex.c, src/os/shared/src/osapi-printf.c, src/os/shared/src/osapi-queue.c, src/os/shared/src/osapi-sockets.c, src/os/shared/src/osapi-task.c, src/os/shared/src/osapi-time.c, src/os/shared/src/osapi-timebase.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/ut-stubs/osapi-utstub-idmap.c
Add a wrapper at the shared layer to provide a common location to check the status of global lock/unlock ops.
All calls to OS_Lock_Global_Impl and OS_Unlock_Global_Impl from the shared modules are replaced with calls to this wrapper.
Notably - this detects and reports the problem described in #474, in case something similar happens in the future.  
Fixes #476
Build and execute all unit tests, and sanity check CFE operations.
Now detects and reports errors in global mutex lock/unlock ops.
If this patch is applied in isolation without any other changes, one will see debug trace generated as it is detecting the …
=> Fix #476, add global lock/unlock wrapper

ut_assert/inc/utstubs.h, ut_assert/src/utstubs.c
Add the capability to store parameter names in addition to pointers as part of the stub argument context data.
Macroize the UT_Stub_RegisterContext function utstubs.h to also pass the parameter name in addition to the pointer.
Add hook-side accessor functions/macros to make it easier and more reliable to get this information from the context data.
Also other minor items:
- Increase max "fixed" args from 4 to 8
- Add convenience macros for variable argument stubs
Fixes #479 
Build and execute unit tests, confirm all passing (baseline).
Update EVS stub and SAMPLE_APP test cases to use new functions and confirm operation.
New features only, does not change existing behavior.
UT Hook functions now have the …
=> Fix #479, add name association to stub arguments

src/tests/timer-add-api-test/timer-add-api-test.c
Fix #381, Add OS_TimerAdd functional test
Added OS_TimerAdd functional test
cFS Dev Server
Yasir Khan
NASA GSFC
=> Fix #381, Add OS_TimerAdd functional test

src/tests/time-base-api-test/time-base-api-test.c
Fix #380, Add OS_TimeBase Api Functional Tests
Added OS_TimeBase Api Functional Tests for OS_TimeBaseCreate, OS_TimeBaseSet, OS_TimeBaseDelete, OS_TimeBaseGetIdByName, OS_TimeBaseGetInfo, OS_TimeBaseGetFreeRun
cFS Dev Server
Yasir Khan
NASA GSFC
=> Fix #380, Add OS_TimeBase Api Functional Tests

src/tests/idmap-api-test/idmap-api-test.c
Add a delay loop to ensure that the child task has executed before continuing with the rest of the test.
This also uses a separate "setup" function to create the resources for the test and adds asserts that the setup worked.
Fixes #493
Execute unit tests and confirm passing.
No more race condition in idmap-api-test.
Centos 6.9 VM (single core)
May want to fast track as this causes occasional CI failures in current master branch.
=> Fix #493, race condition in idmap api test

src/os/inc/osapi-os-core.h, src/os/inc/osapi-os-filesys.h, src/os/inc/osapi-os-loader.h, src/os/inc/osapi-os-net.h, src/os/inc/osapi-os-timer.h
Fix #485 - adds "non-zero" to the out variable description for OS_<obj>Create (and related) API's.
Christopher.D.Knight@nasa.gov
=> Fix #485 - add text to make clear that IDs are non-zero

src/ut-stubs/osapi-utstub-file.c, src/ut-stubs/osapi-utstub-filesys.c, src/ut-stubs/osapi-utstub-printf.c, src/ut-stubs/osapi-utstub-task.c
Did a quick scrub for public OSAL APIs defined in `libosal.a` but not defined in stub library.
Added stub functions for:
```
OS_TaskFindIdBySystemData()
OS_FileSysAddFixedMap()
OS_TimedRead()
OS_TimedWrite()
OS_FileSysAddFixedMap()
```
Required for testing other modules that use these functions. Also correct a name mismatch issue in `OS_TaskGetInfo()`.
Fixes #494
Build and run all unit tests.
No change to behavior or FSW.  Just adds stubs for future use.
Ubuntu 20.04
These were not actively used anywhere yet (otherwise would be a link failure) but likely to become an issue as PSP coverage tests are implemented. …
=> Fix #494, add missing stub functions for OSAL API

ut_assert/inc/utassert.h
Add the following macros for UT assert:
`UtAssert_INT32_EQ` - check equality as 32 bit signed int
`UtAssert_UINT32_EQ` - check equality as 32 bit unsigned int
`UtAssert_NOT_NULL` - check pointer not null
`UtAssert_NULL` - check pointer is null
`UtAssert_NONZERO` - check integer is nonzero
`UtAssert_ZERO` - check integer is zero
`UtAssert_STUB_COUNT` - check stub count
These are all just wrappers around `UtAssert_True` for commonly-used asserts.  The description message is auto generated so it is consistent.
Fixes #502 
Build and run all existing unit tests.
Also test with new PSP coverage tests that use the new macros and confirm they work as described.
No impact to current behavior.  These are just new …
=> Fix #502, Add extra assert macros

ut_assert/src/utstubs.c
Some systems may not provide this type.  Using `unsigned long` instead should be sufficient.
Fixes #509
Build on vxworks
Run all unit tests on native system and on RTEMS.
Ubuntu 20.04
GSFC VxWorks lab build machine (gs582w-cfelnx)
=> Fix #509, Remove uintmax_t usage

README.md, src/os/inc/osapi-version.h
Fast Tracked Changes to Integration Candidate 2020-06-10
Fix #509 
Fix #502 
Bundle CI - https://github.com/nasa/cFS/pull/102/checks
PR #503 - Added the following wrappers macros around `UtAssert_True` for commonly-used asserts:
- `UtAssert_INT32_EQ` - check equality as 32 bit signed int
- `UtAssert_UINT32_EQ` - check equality as 32 bit unsigned int
- `UtAssert_NOT_NULL` - check pointer not null
- `UtAssert_NULL` - check pointer is null
- `UtAssert_NONZERO` - check integer is nonzero
- `UtAssert_ZERO` - check integer is zero
- `UtAssert_STUB_COUNT` - check stub count
PR #510 -  Using `unsigned long` instead of `uintmax_t` to fix support for VxWorks
Ubuntu:Bionic …
=> Fast Track for Integration Candidate 2020-06-10

src/bsp/generic-linux/src/bsp_start.c
Keep the entire argc/argv from the shell.  Do not prune the command name as getopt expects this to be there.
Fixes #499 
Execute unit tests, confirm all passing.
Execute new PSP tests, confirm command line options are being recognized.
Command line options in Linux are recognized, no longer ignored/dropped.
Ubuntu 20.04
=> Fix #499, store all arguments in generic-linux BSP

ut_assert/CMakeLists.txt, ut_assert/inc/utassert.h, ut_assert/inc/utbsp.h, ut_assert/inc/uttest.h, ut_assert/src/utassert.c, ut_assert/src/utbsp.c, ut_assert/src/utglobal.h, ut_assert/src/uttest.c
Add a position independent code (PIC) variant of the ut_assert library, which can be dynamically loaded into other applications rather than running as a standalone OSAL application.  This enables loading UT assert as a CFE library.
This required moving some symbols/functions around.  Mainly, the PIC library does _not_ contain the `utbsp.c` file which has the bindings to the OSAL BSP when running as a standalone app, but everything else should be the same.
Fixes #501 
Build and execute all unit tests.
Also test linking new PIC library into a CFE loadable app and running tests.
No impact to current unit testing which runs UT assert as a standalone app.  
Ubuntu 20.04
**Additional …
=> Fix #501, add PIC library for ut assert

src/os/posix/src/os-impl-binsem.c
The pthread API defines the timeout parameter for the pthread_mutex_timedlock call as an absolute value based on CLOCK_REALTIME.
This introduces a wrapper function to calculate the absolute timeout for this.
Fixes #516 
Build and execute CFE, sanity check CFE operation, and run all unit tests.
Coverage is not affected because there is no coverage test for POSIX.
The timed lock in binary semaphores should now correctly wait for up to 2 seconds for the lock to become available before failing.  The net effect of passing a relative timeout in place of an absolute one meant that the code would not wait, basically turning into a "trylock" instead.
Ubuntu 20.04 …
=> Fix #516, Use absolute timeout for timedlock calls

src/tests/time-base-api-test/time-base-api-test.c
Add requisite cast to printf.  Also use `sizeof()` rather than hardcoded size of 12.
Fix #505 
Build and execute all unit tests
Unit tests pass on RTEMS.
Ubuntu 20.04 
RTEMS 4.11.3 via QEMU/pc686
=> Fix #505, warnings in time base API test

src/os/posix/src/os-impl-tasks.c, src/os/shared/src/osapi-task.c, src/tests/idmap-api-test/idmap-api-test.c, src/unit-test-coverage/shared/src/coveragetest-task.c
Resolve inconsistency in how the stack size is treated across different OS implemntations.  POSIX would enforce a minimum, where RTEMS would not.
With this change the user requested size is passed through to the underlying OS exactly as is, no enforced minimum.
An additional sanity check is added at the shared layer to ensure that the stack size is never passed as 0.
Fixes #506 
Build and execute CFE and sanity test
Build and execute all unit tests.
Also tested creating a task with zero stack size and confirm error is generated on Linux.
The `idmap-api-test` passes on RTEMS.
Attempting to create a task with zero stack now will result in error.
Ubuntu 20.04
RTEMS 4.11.3 via QEMU/pc686 …
=> Fix #506, enforce nonzero stack size

src/tests/timer-test/timer-test.c
Fix #196, Fix timer-test to be able to use OS_MAX_TIMERS value
Changed timer-test to be able to use OS_MAX_TIMERS value on top of the hard-coded NUMBER_OF_TIMERS value.  This will allow the test to be functional even if the OS_MAX_TIMERS value is reconfigured.
cFS Dev Server
Yasir Majeed Khan
NASA GSFC/Emergent Space
=> Fix #196, Fix timer-test to be able to use OS_MAX_TIMERS value

src/ut-stubs/osapi-utstub-sockets.c
Fix #522 - OS_SocketOpen() should, on "success", set sock_id and return a status.
See OS_SocketOpen() definition in https://github.com/nasa/osal/blob/bc73437ea95af54078ba40ce4001a567b1bbc393/src/os/inc/osapi-os-net.h#L232
Christopher.D.Knight@nasa.gov
=> Fix #522 - SocketOpen stub should set sock_id

src/os/posix/inc/os-posix.h, src/os/posix/src/os-impl-tasks.c
The `pthread_attr_setstacksize()` function stipulates that it may fail if the user-supplied stack size is not at least
`PTHREAD_STACK_MIN` and also possibly a multiple of page size.
This partially reverts previous PR #508 and adds back rounding up to `PTHREAD_STACK_MIN` and also adds rounding up to a system page size.  However the check for zero stack still remains at the shared level so attempts to create a task with zero
stack will still fail.  This allows internal helper threads to be created with a default minimum stack size, however.
Fixes #525 
Build and sanity check CFE executing as both normal user and root user.
Execute all unit tests as both normal user and root user.
No failure due to stack size …
=> Fix #525, ensure POSIX stack size meets requirements

README.md, ut_assert/src/utassert.c
Avoids a possible truncation in snprintf call.
Fixes #534 
Build and run unit tests.
No buffer size/truncation warning when building with optimization enabled.
Ubuntu 20.04
=> Fix #534, adjust UT assert buffer sizes

src/unit-test-coverage/CMakeLists.txt
Install use the loop variable (TGT) not TGTNAME for DESTINATION.
Fixes #538 
Build with ENABLE_UNIT_TESTS=TRUE and a configuration with multiple CPUs sharing a single arch+platform config.
Without this fix, the coverage binaries are installed twice to CPU2 but not at all for CPU1.
With this fix, they are correctly installed for CPU1 and CPU2.
Ubuntu 20.04
No change to behavior at all - just an install path fix.
=> Fix #538, correct loop variable for coverage install

src/os/inc/osapi-version.h
Resolve #531 
Bundle CI
Docker-based testing using gcc image
New macros defined. No changes on it's own. When combined with nasa/cfe#771 and nasa/psp#178 then startup reporting looks like 
Ubuntu 
Left in a commented-out section for replacing the version string for official releases. 
None
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Resolve #531, Add baseline and build number

ut_assert/README.txt, ut_assert/inc/utstubs.h
Fixes #547 
Fixes a typo in ut_assert README and clarifies stub documentation.
Christopher.D.Knight@nasa.gov
=> fix #547 - ut_assert doc updates

src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c
Fix #379, Add FileSysAddFixedMap functional API test.
Added FileSysAddFixedMap functional API test
cFS Dev Server
Yasir Majeed Khan
NASA GSFC/Emergent Space
=> Fix #379, Add FileSysAddFixedMap functional API test

ut_assert/inc/utlist.h, ut_assert/inc/uttest.h, ut_assert/src/utbsp.c, ut_assert/src/utglobal.h, ut_assert/src/utlist.c, ut_assert/src/uttest.c
Clean up and Refactor the internal list storage structures to support having multiple list heads/groups.  Define a separate list/group for setup, normal test, and teardown.
The existing UtTest_Add() routine maps to the normal test group. Added a UtTest_AddSetup() and UtTest_AddTeardown() routine that maps to the setup and teardown group, respectively.
The existing UtTest_Run() routine then merges the groups and executes the full suite of tests.
This allows separate, dynamic registration of test setup and teardown routines which are executed before and after the normal test routine, which can create and delete any global/common test prerequisites.
Fixes #550 
Build and run all unit tests
Update a unit test to additionally register …
=> Fix #550, add function groups to ut assert

src/tests/network-api-test/network-api-test.c
fix #373, Add OSAL network APIs missing functional tests
fix #378, OS_TimedRead and OS_TimedWrite missing functional tests
Added OSAL network  and OS_TimedRead and OS_TimedWrite missing functional tests.
Standard build and ran unit tests.
cFS Dev Server
**Contributor Info** 
Yasir Majeed Khan
NASA GSFC/Emergent Space
=> fix #373, Add OSAL network APIs missing functional tests and fix #378 OS_TimedRead and OS_TimedWrite missing functional tests

src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-binsem.c, src/os/shared/src/osapi-countsem.c, src/os/shared/src/osapi-dir.c, src/os/shared/src/osapi-file.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-module.c, src/os/shared/src/osapi-mutex.c, src/os/shared/src/osapi-queue.c, src/os/shared/src/osapi-task.c, src/os/shared/src/osapi-time.c, src/os/shared/src/osapi-timebase.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/ut-stubs/osapi-utstub-idmap.c
Remove repetitive clearing of the global ID and unlocking global table and replace with common implementation in the
idmap source file.  In addition to removing repeated logic, this makes deletion more like an inverse of creation, and provides
a common/single point where additional deletion-related logic can be added.
Fixes #564 
Build and sanity test CFE
Confirm all unit tests
No impact to external API or behavior.  Internal code consolidation only.
Ubuntu 20.04
See also #540 and #532 
=> Fix #564, consolidate delete finalization code

src/os/shared/inc/os-shared-idmap.h, src/ut-stubs/osapi-utstub-idmap.c
These internal functions were no longer used or defined but the prototype and stub were still present.  This removes them.
Fixes #557 
Compile and run unit tests.
None - unused/stale code cleanup.
Ubuntu 20.04
=> Fix #557, remove OS_ObjectIdMap/Unmap prototype and stub

src/os/shared/src/osapi-task.c
If this routine fails then return the error to the caller, which will also prevent the task from starting.
Fixes #565 
Build and run all unit tests incl. coverage.
No impact to behavior, as no known way to force this error, but will correctly propagate an error if one were to occur.
Ubuntu 20.04
=> Fix #565, propagate return code from OS_TaskRegister_Impl()

src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Fix #581 - Max timer create test was using OS_MAX_TIMERS (the limit for adding timers to a time base), but creating timers is limited by OS_MAX_TIMEBASES since the create adds a new time base.
Build and ran osal_timers_UT, passed without TSF
All unit tests now pass
- Versions: bundle main + this commit
TSF failures started getting reported as test failures as part of #579.  This PR should be merged with (or before) #579 or unit tests will fail.
None
=> Fix #581, Use OS_MAX_TIMEBASES for max timer create unit test

ut_assert/src/utbsp.c
Fix #537 - fail tests on startup or tear down failures... these are failures, just a different severity (likely mean the test didn't work as expected and needs to be fixed)
Built tests with a known startup failure, test failed as expected
Now will fail on startup/tear down failures
- Versions: bundle main (+ cfe/osal main) + this change
None
None
=> Fix #537, Fail tests on startup and tear down failures

src/os/inc/osapi-os-core.h, src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-idmap.c
Move this existing function into the public API, as it is performs more verification than the `OS_ConvertToArrayIndex`
function.
Fixes #589 
Build and sanity test CFE
Run all tests
None. 
Ubuntu 20.04
No change to function, just moved to public API.
=> Fix #589, promote OS_ObjectIdToArrayIndex to public API

src/os/inc/osapi-version.h
Fix #584
Revision version number now reports `99` during development versions. ES Housekeeping data reports `6.7.99` in the version string.
Built and ran on Docker container. 
Also see nasa/cfe#830
None
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Fix #584, Set Revision to 99 for development builds

ut_assert/inc/utassert.h
Fix #604 - adds the macro
Used the macro in work related to nasa/cfe#903 (built and ran unit tests locally using it)
Additional macro available
- Versions: main bundle + this commit
None.
None.
=> Fix #604, Add ut_assert address equal macro

src/os/inc/osapi-os-core.h, src/os/shared/inc/os-shared-common.h, src/os/shared/src/osapi-common.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-task.c, src/ut-stubs/osapi-utstub-common.c
Adds an event callback mechanism to certain state changes in OSAL.  This allows the CFE PSP to be notified at these points, and therefore it can add platform-specific functionality.  This can, for instance, set the task name as requested in #532 or set the processor affinity in a multi-core setup (TBD).
Fixes #540 
Create an event handler in the pc-linux CFE PSP and register it, and print out each event received.  Confirm events are generated as expected, and that it didn't break the FSW in any way.
Note - Not completely tested yet -- this is mainly a proof of concept and pushed for design review at this time.
Adds ability to implement custom platform-specific functionality for defined events.
**System(s) …
=> Fix #540, add event callback framework

src/os/rtems/src/os-impl-binsem.c, src/os/rtems/src/os-impl-countsem.c, src/os/rtems/src/os-impl-queues.c, src/os/rtems/src/os-impl-tasks.c
Correct issues involving recent OS_Milli2Ticks change.
Note - for OS_TaskDelay it is important that this doesn't degrade into a no-op.  So if OS_Milli2Ticks fails here, this returns the
error but still also does a non-zero delay.
Build and sanity check CFE under RTEMS
Builds and runs correctly
RTEMS 4.11.3 + pc686 BSP target (QEMU) using Ubuntu 20.04 build host
Includes the typo fix in #614 plus others.
=> Fix #615, RTEMS build issues

src/os/rtems/src/os-impl-binsem.c, src/os/rtems/src/os-impl-console.c, src/os/rtems/src/os-impl-countsem.c, src/os/rtems/src/os-impl-mutex.c, src/os/rtems/src/os-impl-queues.c, src/os/rtems/src/os-impl-tasks.c, src/os/rtems/src/os-impl-timebase.c
Change use of uint32 for ID to the correct typedef.  Also use ObjectIdFromInteger/ObjectIdToInteger where it is intended to
convert these values to integers e.g. for the "name" fields in RTEMS.
Fixes #618 
Build and sanity test CFE on RTEMS
Confirm all unit tests working
None
RTEMS 4.11.3 / pc686 (QEMU) via Ubuntu 20.04 build host
For consistency with all other modules
=> Fix #618, Use osal_id_t in RTEMS implementation

src/os/inc/osapi-os-filesys.h, src/os/shared/src/osapi-file.c, src/tests/file-api-test/file-api-test.c, src/unit-test-coverage/shared/src/coveragetest-file.c, src/unit-tests/oscore-test/ut_oscore_select_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/ut-stubs/osapi-utstub-file.c
These functions are replaced by OS_OpenCreate, which implements both functions via flags, and follows the correct OSAL API patterns.
Fixes #556 
Build and run all tests, sanity check CFE
Check coverage of file-related APIs (still 100%)
`OS_open()` and `OS_create()` are deprecated.
Ubuntu 20.04
This initially puts the items inside an `OSAL_OMIT_DEPRECATED` block for review and testing, like has been done traditionally.
Should discuss at CCB whether this should become a hard-cut given that the next release will be a major one.
Although the previous discussions on the topic agreed to hard cut at major releases, these are such widely-used routines that this will …
=> Fix #556, Deprecate OS_open and OS_creat

src/os/inc/osapi-version.h
Fix #584 for Bootes
Built and ran locally based on bundle tag for bootes-rc1
Built in CI, See https://travis-ci.com/github/astrogeco/cFS/builds/189834136
Revision version number now reports `99` during development versions. ES Housekeeping data reports `6.7.99` in the version string.
Built and ran on Docker container. 
Also see nasa/cfe#830
None
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Apply #585 to Bootes, Set Revision to 99 for development build

src/os/shared/inc/os-shared-mutex.h, src/os/shared/src/osapi-mutex.c
If `OS_DEBUG` is enabled, this adds a message if mutex give/take actions occur outside the expected sequence.  In particular,
this warns if a task takes a mutex more than once.
Fixes #623 
Build and sanity test CFE with debug events enabled, confirm normal boot and operation.
Send "remove packet" request to TO_LAB.
Confirm warning is generated as follows (this is a known issue in CFE doing multiple locks):
OS_MutSemTake():216:WARNING: Task 65547 taking mutex 327685 while owned by task 65547
If debugging is enabled this now informs the user (via the debug console) if a lock is taken more than once.
It will also warn if a lock is given by a different task than what originally took it. …
=> Fix #623, add debug messages for mutex double locks

src/os/inc/osapi-os-filesys.h, src/os/portable/os-impl-bsd-sockets.c, src/os/portable/os-impl-posix-files.c, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-select.c, src/unit-test-coverage/portable/src/coveragetest-posix-files.c, src/unit-test-coverage/ut-stubs/inc/OCS_stat.h, src/unit-test-coverage/ut-stubs/override_inc/stat.h, src/unit-test-coverage/ut-stubs/src/posix-stat-stubs.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c
- Turned all FIXME comments into issues (and removed FIXME)
- Fix #333: security/filename race issue resolved by opening file and acting on descriptor (had to add fstat stub)
- Fix #327: squashed the minor recommended bugs
Built and ran unit tests, passed.
None
- Versions: bundle main + this commit
#630, #632 - new issues from FIXME
#631 - uncovered missing functional test on OS_chmod
None
=> Fix #327 and #333, Squash LGTM warnings

ut_assert/inc/utassert.h
Changed all UtAssert macros to take variable string arguments, feature request #628 
Steps taken to test the contribution, cFS/main branch commit 20097ef64e455ace25a1535ea43090a739eb7c0c:
https://github.com/nasa/cFS/
1. make clean
2. make ENABLE_UNIT_TESTS=TRUE SIMULATION=native
3. make test
4. All cFE unit tests pass
UtAssert_True wrapper around call will no longer be necessary to accommodate dynamic string output, thus removing the double assert.  UtAssert macros will now be able to offer more information by themselves.
PC, RHEL 7.6 …
=> Fix #628, Update UtAssert macros with dynamic string formatting

src/os/shared/inc/os-shared-module.h, src/os/shared/src/osapi-module.c
Ensure that the handle is not NULL before invoking `dlclose()`.  In particular the handle will be NULL for static modules.
Fixes #637 
Build and sanity test CFE with apps linked statically.
- Shutdown after CTRL+C occurs normally (no segfault)
- Also confirmed that specifying an incorrect entry point symbol in startup script also benign.  (because a bad entry point also causes module to be "unloaded" as part of cleanup, which triggered the bug too)
Ubuntu 20.04 
i686-rtems4.11 / pc686 via QEMU
This issue only affects statically linked apps, which "go through the motions" of module loading for consistency in operation, but do not actually load a module - because …
=> Fix #637, fix OS_ModuleUnload for static modules

src/os/inc/osapi-os-loader.h, src/os/portable/os-impl-no-symtab.c, src/os/portable/os-impl-posix-dl-loader.c, src/os/portable/os-impl-posix-dl-symtab.c, src/os/shared/inc/os-shared-module.h, src/os/shared/src/osapi-module.c, src/os/vxworks/src/os-impl-symtab.c, src/unit-test-coverage/shared/adaptors/inc/ut-adaptor-module.h, src/unit-test-coverage/shared/adaptors/src/ut-adaptor-module.c, src/unit-test-coverage/shared/src/coveragetest-module.c, src/unit-test-coverage/ut-stubs/src/osapi-loader-impl-stubs.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.h, src/unit-tests/osloader-test/ut_osloader_test.c, src/ut-stubs/osapi-utstub-module.c
Add a "flags" parameter to OS_ModuleLoad() and use this to indicate the desired symbol visibility - either GLOBAL (0, the default, and matches current behavior) or LOCAL, which means symbols are hidden from other modules.
This is intended as a "hint" to OSAL as to how the module will be used - LOCAL prevents other modules from binding to symbols in this module, thereby ensuring/preserving the ability to unload in the future.  CFE should use LOCAL flag for apps, and GLOBAL flags for libraries, which are typically not ever unloaded.
Fixes #641
Sanity check CFE (update/patch required update to CFE to add flags parameter on API call)
No impact to behavior if flags are passed as 0. …
=> Fix #641, add OS_ModuleLoad flags

src/os/portable/os-impl-posix-files.c
VxWorks only provides the 3 argument form of `open()`.  Passing 0 as the mode solves the build issue.  This parameter is ignored when not creating a file.
Fixes #655 
No behavior change.  Fixes build issue on VxWorks 6.9
VxWorks 6.9
=> Fix #655, use 3 argument form of open

src/os/vxworks/inc/os-impl-tasks.h, src/os/vxworks/src/os-impl-tasks.c
This should avoid any inconsistencies in the event that the memory address translates to a negative numeric value.
Fixes #651 
None - just avoids possible sign conversions.
Ubuntu 20.04
VxWorks 6.9
=> Fix #651, use unsigned types in VxWorks stack calculation

src/tests/timer-test/timer-test.c
Fixes #586, added a one shot timer. 
Added a 5th timer to functional test to test the one shot (zero-length time interval) case.
Build and run unit test.
No behavior change 
Ubuntu 20.04
=> Fix #586, Add one shot timer functional test

src/bsp/pc-rtems/CMakeLists.txt, src/bsp/pc-rtems/src/bsp_start.c, src/bsp/pc-rtems/src/pcrtems_bsp_internal.h, src/os/rtems/inc/os-rtems.h, src/os/rtems/src/os-impl-heap.c, src/os/rtems/src/os-impl-loader.c
Fix #608
This change adds support for RTEMS 5.1 in the OSAL.
The change provides defines and necessary ifdefs so RTEMS 4.11 can continue to be supported.
Following the instructions in the pc-rtems PSP:
https://github.com/nasa/PSP/blob/main/fsw/pc-rtems/README.txt
and the updated README_RTEMS_5.txt from PSP pull request 197, I built the RTEMS toolchains, the pc686 BSPs and cFS bundle for both RTEMS 4.11 and RTEMS 5.x. I then ran the bundle on both RTEMS 5.1 and RTEMS 4.11 on QEMU x86.
Note, that for RTEMS 5, the latest RTEMS 5.x git repository has to be used, since there was an RFS file system bug that prevented the bundle from working on the pc-rtems platform.
I did not run the complete set of tests yet on RTEMS 5.1.
**Expected behavior …
=> Fix #608 - Add RTEMS 5.x support

src/os/portable/os-impl-posix-files.c
Fixes #650 by checking for either read or write access instead of just read access 
Used the Chmod tests I am building in another branch that found this issue in the first place. 
-No changes 
Ubuntu 20.04
=> fix #650 OS_chmod uses read or write access.

src/tests/file-api-test/file-api-test.c
Fixes #631 by adding new function tests
These new test, but ran them on the branch from #650 
The new tests added to make test
Dependant on #650 
Ubuntu 20.04
=> Fix #631, Add new functional tests for OS_chmod

src/os/posix/src/os-impl-console.c, src/os/rtems/src/os-impl-console.c, src/os/vxworks/src/os-impl-console.c
Fix #120 
Replaced condition on forever loops to end on shutdown. 
Built and ran unit tests for posix, built on vxworks (planning to build on RTEMs using the latest setup instructions...)
- Loop will exit on shutdown
- Hardware: cFS Dev server
- Versions: Bundle main + this change
What about also checking for a semaphore error on posix/rtems (or at least non-interrupt)?  Would make it consistent with vxworks.
None
=> Fix #120, Exit console loop on shutdown

src/os/posix/src/os-impl-idmap.c, src/os/rtems/src/os-impl-idmap.c, src/os/shared/inc/os-shared-common.h, src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-idmap.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/ut-stubs/src/osapi-common-impl-stubs.c
Reworks the POSIX global lock implementation.
- Does not change the POSIX signal mask when locking/unlocking the global.  Aside from being unnecessary, there was also a race condition in here (Fixes #673)
- Adds a condition variable to the global lock structure.  In the event that there is more than task competing for access to the same object, this allows the second task to be woken immediately instead of polling for a change (Fixes #677).
Build and run all unit tests
No longer changing signal masks repeatedly/unexpectedly.  (may be relevant to some BSP/driver developers)
Ubuntu 20.04
RTEMS 4.11 …
=> Fix #673 and #677, update global locks

src/os/posix/src/os-impl-timebase.c
Fix #686 - Now uses errno instead of status return  from clock_getres with strerror reporting
Built and ran unit tests on linux, which doesn't mean much since it doesn't include this code in functional or coverage testing.
Requesting retest from @ericgilligan-nasa
Fixed error message
None.
None.
=> Fix #686, Use errno in clock_getres error reporting

src/os/posix/src/os-impl-tasks.c
Fix #569 - Checks return of sysconf for error and if so reports, only sets PageSize on success.
None since sysconf should never fail, but if it does provides mechanism to avoid error propagation
None.
None.
=> Fix #569, Check and report sysconf error return

src/unit-tests/oscore-test/ut_oscore_countsem_test.c
Fix #542 - avoids a potential unit test failure if an invalid semaphore value can not be passed in
Build and run unit tests, passed
None.
Unable to reproduce error from issue (requires feedback from @mbenson1) but this fix avoids a potential error case.
None
=> Fix #542, Avoid UT failure if SEM_VALUE_MAX >= UINT32_MAX

src/tests/select-test/select-test.c
Fixes #377 
Added new functional tests for the the select and select multiple functions. 
Ran the new tests. 
None
Ubuntu 20.04
=> Fix #377, Add "OSAL Select" functional tests

src/os/vxworks/CMakeLists.txt, src/os/vxworks/src/os-impl-common.c, src/os/vxworks/src/os-impl-dirs-globals.c, src/os/vxworks/src/os-impl-dirs.c, src/os/vxworks/src/os-impl-tasks.c, src/unit-test-coverage/vxworks/CMakeLists.txt, src/unit-test-coverage/vxworks/adaptors/CMakeLists.txt, src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-dirtable-stub.c, src/unit-test-coverage/vxworks/src/coveragetest-dirs-globals.c, src/unit-test-coverage/vxworks/src/coveragetest-dirs.c
This is a more Joe-approved vxworks7 addition without the copy of the code.
None yet. I'm going to bed. But I wanted to look at it with the CCB. I will try and do testing before the CCB.
Steven Seeger, Embedded Flight Systems, Inc.
=> Fix #610, Add vxworks7 support

src/os/inc/osapi-bsp.h, src/os/inc/osapi-idmap.h
Fix #726 - closed group and removed old group.
`make usersguide` locally and confirmed no warnings
No warnings on user's guide build
None
None
=> Fix #726, Resolve user's guide generation warnings

src/os/shared/src/osapi-idmap.c
Fix #730 - suppresses the invalid warning.
Re-ran cppcheck and observed no warnings
None except no warning
None
None
=> Fix #730, Suppress invalid redundantAssignment warning from cppcheck

ut_assert/inc/utassert.h
Fix #574 - document UtAssert_Message parameters, also adds see also for helper macros
CI, comment change only.
None
N/A
Worth considering making this internal, no identified use case for direct call.  Would be confusing to output any message other than info/debug.
None.
=> Fix #574, Document UtAssert_Message parameters

src/tests/select-test/select-test.c
fixes #707
Removed Sem flush and changed it to sem give to prevent a rare race condition. 
Change the port numbers to be different from network test for when test are run in parallel. 
Ran the unit tests in parallel 
Test shouldn't lock or fail 
Ubuntu 20.04
=> Fix #707 change sem flush to solve race condition

src/unit-tests/inc/ut_os_support.h, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfile-test/ut_osfile_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Fix #712 - replaces UT_OS_LOG with UtPrintf (it was just a duplicated macro)
Standard build and run of unit tests
No change, just code duplication cleanup
None
None
=> Fix #712, Replace UT_OS_LOG with UtPrintf

src/os/posix/inc/os-impl-idmap.h, src/os/posix/src/os-impl-idmap.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/os/rtems/inc/os-impl-idmap.h, src/os/rtems/src/os-impl-idmap.c, src/os/rtems/src/os-impl-tasks.c, src/os/shared/inc/os-shared-common.h, src/os/shared/inc/os-shared-idmap.h, src/os/shared/inc/os-shared-task.h, src/os/shared/src/osapi-file.c, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-module.c, src/os/shared/src/osapi-sockets.c, src/os/shared/src/osapi-task.c, src/os/vxworks/inc/os-impl-idmap.h, src/os/vxworks/inc/os-vxworks.h, src/os/vxworks/src/os-impl-idmap.c, src/os/vxworks/src/os-impl-tasks.c, src/os/vxworks/src/os-impl-timebase.c, src/tests/osal-core-test/osal-core-test.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/ut-stubs/src/osapi-task-impl-stubs.c, src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-idmap.c, src/unit-test-coverage/vxworks/src/coveragetest-idmap.c, src/ut-stubs/osapi-utstub-idmap.c
Address multiple issues with the OSAL global table management - general cleanup and bug fixes.
Fixes #702 - use iterators whenever possible
Fixes #645 - use an unlock key rather than task ID so OS_TaskExit() doesn't trigger a warning
Fixes #701 - general cleanup of lock/unlock impl and remove redundant logic
Fixes #703 - unlock global tables during create/delete 
Fixes #642 - keep threads "attached" in POSIX, so they can be joined when deleted.
Build and run all tests for all platforms
Sanity check CFE and also confirmed RELOAD/RESTART commands are working correctly.
No longer triggers warning with OS_TaskExit() on VxWorks (see #645)
OS_TaskDelete() on POSIX does not return until the task has actually exited …
=> Fix #642, 645, 701, 702, 703 - OSAL global table management

src/os/portable/os-impl-posix-files.c, src/unit-test-coverage/portable/src/coveragetest-posix-files.c, src/unit-test-coverage/ut-stubs/inc/OCS_errno.h, src/unit-test-coverage/ut-stubs/override_inc/errno.h
Implement better error translations in the OS_FileChmod_Impl() function.
Also corrects a file handle leak.
This makes it return OS_ERR_NOT_IMPLEMENTED when run on a file system that does not have permissions, which in turn causes the unit test to be skipped rather than fail.
Fixes #708 
Build and run all unit tests
The chmod test is now skipped on VxWorks rather than failing.
VxWorks 6.9 (mcp750)
=> Fix #708, chmod error handling

src/os/shared/src/osapi-sockets.c, src/unit-test-coverage/shared/src/coveragetest-sockets.c
Add parameter check to OS_SocketSendTo and adjust coverage test to validate.
Fixes #544 
None
Ubuntu 20.04
=> Fix #544, add pointer check

src/os/inc/osapi-filesys.h, src/os/shared/inc/os-shared-filesys.h, src/os/shared/src/osapi-filesys.c, src/tests/file-api-test/file-api-test.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.h, src/unit-tests/osfilesys-test/ut_osfilesys_test.c, src/ut-stubs/osapi-utstub-filesys.c
Add OS_FileSysStatVolume as replacement for OS_fsBytesFree and OS_fsBlocksFree.
Fixes #573
Run all unit tests.
New API for getting stats on file system.
Uses existing OS_FileSysStatVolume_Impl call - just exposes it in public API.
Ubuntu 20.04
This PR is only adding a new API, it is not (yet) deprecating the existing OS_fsBlocksFree/OS_fsBytesFree calls.  Applications and CFE will need an update before these calls can be deprecated, but the new API needs to be in place before the existing refs can be fixed.
=> Fix #573, add OS_FileSysStatVolume

src/os/shared/src/osapi-common.c
When cleaning up for shutdown, delete resources that have a task/thread first, followed by other resource types.  This helps avoid possible dependencies as running threads might be using the other resources.
Fixes #471
Sanity check CFE, ensure shutdown works as expected
No visible impact ... internally the tasks are deleted first during shutdown, which only has an impact if/when tasks are actively using other OSAL resources.
=> Fix #471, order of operations for delete all

src/os/inc/osapi-filesys.h, src/os/vxworks/src/os-impl-filesys.c, src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
The mount/unmount implementation was not adequately checking for and handling the `FS_BASED` (pass -through) mapping type - which should be mostly a no-op.  But to be consistent with POSIX it should also create a mount point directory if it does not already exist when using this mapping type.
Adds a documentation note to `OS_FileSysAddFixedMap()` regarding the limitation that the virtual mount point cannot be empty - so `OS_FileSysAddFixedMap(.., "/", "/")` does not work - never did.  However `OS_FileSysAddFixedMap(.., "/", "/root")` does work and allows one to open files in the root as "/root/<file>" from OSAL applications.
Fixes #580
Build and run all unit tests on native
Sanity check CFE
Confirm behavior of `OS_FileSysAddFixedMap()` + …
=> Fix #580, improve FS_BASED mounts on VxWorks

src/os/vxworks/src/os-impl-tasks.c
Fix #606 - store taskTCB return in a `void *`, then cast to `OS_impl_task_internal_record_t *` just for the pointer math to avoid a strict alignment compiler error
Note the error was observed with cast-align=strict on Ubuntu 20.04 with ENABLE_UNIT_TESTS=true
Built without the error after fix.  Built/ran unit tests on Ubuntu 18.04 and they all passed.
None other than avoid compiler error
- OS: Ubuntu 18.04 (and 20.04 to confirm strict alignment error resolved)
- Versions: Bundle + this commit
None
None
=> Fix #606, Resolve cast-align error in VxWorks OS_TaskGetId_Impl

src/os/inc/common_types.h
Fix #644 - removes the non-portable OS_PACK and OS_ALIGNED macros
Built and ran unit tests, no issues (no dependencies in bundle)
None
None
None
=> Fix #644, Remove alignment macros

src/bsp/pc-rtems/src/bsp_console.c, src/os/rtems/src/os-impl-network.c, src/os/rtems/src/os-impl-queues.c, src/os/rtems/src/os-impl-tasks.c
Fixes #732
change prototypes should be the same, from uint32 to size_t
Build on RTEMS 5
Able to build
Ubuntu 20.04 as build host for RTEMS 5.0.0
Dependant on nasa/osal#704 to successfully build
=> Fix #732, change uint32 to size_t

src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-timebase.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/shared/src/coveragetest-timebase.c
Add OS_CHECK_POINTER macros to OS_ConvertToArrayIndex and OS_TimeBaseGetFreeRun.
Fixes #445
None
Ubuntu 20.04
=> Fix #445, add pointer parameter checks

src/os/inc/osapi-clock.h, src/os/inc/osapi-file.h, src/os/portable/os-impl-posix-files.c, src/os/portable/os-impl-posix-gettime.c, src/os/shared/src/osapi-clock.c, src/tests/timer-add-api-test/timer-add-api-test.c, src/tests/timer-test/timer-test.c, src/unit-test-coverage/portable/src/coveragetest-posix-files.c, src/unit-test-coverage/portable/src/coveragetest-posix-gettime.c, src/unit-test-coverage/shared/src/coveragetest-clock.c, src/unit-test-coverage/ut-stubs/inc/OCS_stat.h, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.c, src/ut-stubs/osapi-utstub-clock.c
Initially the first commit just adds access functions to convert/extract different units from an `OS_time_t` value - so that other code in CFE/PSP/Apps can be updated to use the access functions and thereby not break when the internal time definition changes.  There will then be a second commit that updates the actual time format.
It also uses OS_time_t in the "stat" structure used by the file module rather than having this be a `int32`.
Minor detail - also updates the pointer argument to `OS_SetLocalTime()` to be `const`
Fixes #429
Initially just a set of new access functions - no impact to behavior
Eventually will change the internal format of `OS_time_t` which will break any …
=> Fix #429, add OS_time_t access functions

src/tests/select-test/select-test.c
Fix #755 
Removed the second semaphore that was trying to make sure the subtasks finish closing and instead just forcibly close them from the main task. 
Ran the select test 300 times on my computer with no fails. 
Test should not fail or hang 
Ubuntu 20.04
=> Fix #755, resolve subtasks not ending on time

src/tests/select-test/select-test.c
Fixes #699
Fixed the formatting to correctly build. Have been unable to test on RTEMS 4
Tested on RTEMS 5 and worked. 
Able to build 
Ubuntu 20.04 RTEMS 5
Needs to be tested on RTEMS 4
=> Fix #699, format printf correctly

SECURITY.md
Fixes #743 
Created a draft of a security policy markdown file for OSAL. The purpose of a security policy is to inform users on how to submit bugs or vulnerabilities. It is ideal to include a section for supported versions.
Optional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities
References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy
=> Fix #743, Create OSAL Security Policy Markdown

src/ut-stubs/osapi-utstub-printf.c
Fix #746 - added UtDebug in OS_printf stub
Built tests and confirmed debug output
Outputs the OS_printf input as a debug message from stub
None
None
=> Fix #746, Add UtDebug message from OS_printf stub

ut_assert/inc/uttest.h
Fix #577 - adds documentation to the UtTest_Add API that nesting (UtTest_Add from within an added test) silently fails.
None, documentation only.  
None
N/A
nasa/cFE#841
None
=> Fix #577, Document nested tests not supported

src/tests/file-api-test/file-api-test.c
Fix #761, Terminate string in TestReadWriteLseek
Initialized the character arrays to known values, observed missing termination in report, fixed w/ this comment and observed the garbage no longer being reported.
No impact to main code, UT only (and just the report, test passes either way).
- cFS Dev Server
None
None
=> Fix #761, Terminate string in TestReadWriteLseek

src/os/inc/osapi.h
Fix #757, Readd extern C in osapi.h to support C++ use
Build and unit test, passes.
@johnphamngc - could you test in C++ context and confirm this resolves your issue?
Works to include header in C++ again, no other functional change
None
None
=> Fix #757, Read extern C in osapi.h to support C++ use

src/unit-test-coverage/portable/src/coveragetest-posix-files.c, src/unit-test-coverage/shared/src/coveragetest-binsem.c, src/unit-test-coverage/shared/src/coveragetest-countsem.c, src/unit-test-coverage/shared/src/coveragetest-file.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/shared/src/coveragetest-mutex.c, src/unit-test-coverage/shared/src/coveragetest-queue.c, src/unit-test-coverage/shared/src/coveragetest-select.c, src/unit-test-coverage/shared/src/coveragetest-sockets.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-test-coverage/shared/src/coveragetest-time.c, src/unit-test-coverage/shared/src/coveragetest-timebase.c, src/unit-test-coverage/vxworks/src/coveragetest-common.c, src/unit-test-coverage/vxworks/src/coveragetest-console.c, src/unit-test-coverage/vxworks/src/coveragetest-filesys.c, src/unit-test-coverage/vxworks/src/coveragetest-idmap.c, src/unit-test-coverage/vxworks/src/coveragetest-loader.c, src/unit-test-coverage/vxworks/src/coveragetest-no-module.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c, src/unit-test-coverage/vxworks/src/coveragetest-tasks.c, src/unit-test-coverage/vxworks/src/coveragetest-timebase.c, ut_assert/inc/utstubs.h, ut_assert/src/utstubs.c
Fixes #724  
Rename UT_ClearForceFail to UT_ClearDefaultValue
Fixes #722
Update the comments of UT_SetDefaultReturnValue to match the more general function
There will be more pull requests from other sub modules that are dependant on this. 
Ubuntu 20.04
=> Fix #724, #722, rename ut clear force fail

ut_assert/src/utassert.c, ut_assert/src/utbsp.c
Fixes #591
added test teardown failures to the test summary 
also changed the print out to use the same style as startup failures. 
Used a test that always fails teardown and verified that it was reported in the test summary. 
N/A
Ubuntu 20.04
=> Fix #591, add test teardown failure to test summary

src/ut-stubs/utstub-helpers.c, src/ut-stubs/utstub-helpers.h
Fix #753 - removes UT_CheckForOpenSockets which was an old hack to check if unit tests cleaned up sockets.  No longer applicable since the UT framework resets the state for each unit test.
Built and ran unit tests with nasa/cfe#1085
None
-  Versions: Bundle main + nasa/cFE#1085 + this commit
None
None
=> Fix #753, Remove UT_CheckForOpenSockets

src/tests/file-api-test/file-api-test.c
fixes #685
Changed the file create to read write to work on RTEMS
Ran the test on RTEMS 5
Test should pass
Ubunto 20.04, RTEMS 5
Alex Campell GSFC
=> Fix #685 change file create to use read write

src/tests/network-api-test/network-api-test.c
Fixes #692
fixed the or statement to correctly compare against both options. 
will correctly cath failures when they happen
Ubuntu 20.04
=> Fix #692, fix or statements

src/tests/queue-test/queue-test.c
Fixes #229 
Generalized queue timeout test to also test message queue functionality 
Build and run the unit tests 
Adds 2 seconds to the unit tests 
Ubuntu 20.04
=> Fix #229, mqueue functional test

src/os/inc/osapi-clock.h, src/unit-test-coverage/shared/src/coveragetest-clock.c
Use a single 64-bit tick counter to implement `OS_time_t`, rather than a split 32 bit seconds + 32 bit microseconds counter.
This benefits in several ways:
- increases the timing precision by 10x (0.1us ticks)
- increases the representable range by 400x (+/-14000 yrs)
- simplifies addition/subtraction (no carry over)
- avoids "year 2038" bug w/32-bit timestamps
Fixes #429 
Build and run all unit tests, sanity check CFE
None
RTEMS 4.11 + pc686 (qemu)
This is the final step listed in issue #429, and it depends on several dependencies being merged already:
- PR nasa/cfe#1058
- PR nasa/psp#228
- PR nasa/osal#723
It is submitted as a separate PR …
=> Fix #429, OS_time_t with single tick counter

src/tests/file-api-test/file-api-test.c, src/tests/select-test/select-test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osloader-test/CMakeLists.txt
Fix #760 - Installs the modules used in unit testing and added removal of files where they were left-over after tests completed
Built and ran unit tests (also installed and ran osal_loader_UT from build/exe/* directory).  Confirmed no files were left over in /dev/shm
UT's work and clean up files
None
None
Ping @jhnphm
=> Fix #760, Install modules and clean up files for unit tests

.github/workflows/codeql-build.yml
Fix #775 - adds CodeQL analysis
Differences from bundle - just builds osal, has timeout
Ran on fork
Adds Code QL analysis on push to main and pull requests (to main)
CI
None
None
=> Fix #775, Add CodeQL analysis to workflow

src/tests/osal-core-test/osal-core-test.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Fix #785 - cleans commented out code (all from test code)
Build/execute unit test, passes
None, just avoids static analysis warnings
- Hardware: [e.g. PC, SP0, MCP750]
- OS: [e.g. Ubuntu 18.04, RTEMS 4.11, VxWorks 6.9]
- Versions: [e.g. cFE 6.6, OSAL 4.2, PSP 1.3 for mcp750, any related apps or tools]
Would really benefit from ASSERT macro in cFE... maybe consider moving/consolidating these general macros?  Almost all the debug code that was commented out would be better replaced by ASSERT.
None
=> Fix #785, Clean commented out code

src/os/shared/src/osapi-idmap.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/ut-stubs/osapi-utstub-bsp.c, src/ut-stubs/osapi-utstub-idmap.c
Fix #783, Simply adds initialization where flagged by static analysis as possibly uninitialized
No functional change to non-test code, avoids returning uninitialized values from stubs.
None
None
=> Fix #783, Initialize locals flagged in static analysis

src/os/shared/src/osapi-errors.c, src/os/shared/src/osapi-network.c
Fix #788 - fixed two locations with local return code defined as uint32, should be int32 (or eventually the status type)
No functional change, just resolves warnings
Static analysis warning
None
=> Fix #788, Resolve coercion alters value warnings

src/os/portable/os-impl-bsd-sockets.c
Fix #793, Just simplifies switch statements based on previous checks.  Can always be expanded again if additional cases are implemented.
Static analysis warning fix
None
=> Fix #793, Remove unreachable code in OS_SocketOpen_Impl for BSD socket

ut_assert/inc/utstubs.h
Fix #781 - terminates the variadic lists with NULL in the unit test macros
Build and execute unit tests, pass
Avoids CodeQL warning
None
None
=> Fix #781, Terminate UT macro variadic lists

src/os/posix/src/os-impl-binsem.c
Fix #803 - adds a check to send the semaphore to avoid unreachable code, basically a non-op placeholder to avoid refactoring unreachable code which would make it less future-proof
None, avoids static analysis warning and uncoverable code
Eventually when coverage is added to posix this will help meet the 100% goal
None
=> Fix #803, Add check of semaphore to avoid unreachable code in posix OS_BinSemCreate_Impl

src/os/shared/src/osapi-printf.c
Fix #790 - now returning status from OS_ConsoleAPI_Init so debug warnings will get reported correctly on errors
Build and executed unit tests, passed (note the OS_ConsoleAPI_Init test does not check status)
Will send debug message on error
See #791 to add full branch coverage to unit tests w/ return checking
None
=> Fix #790, Return status from OS_ConsoleAPI_Init

src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c
Fix #777, declares DummyVec as static to avoid warning (and returning stack allocated memory) when returning VecTbl.
Build and execute unit tests, passed.
Bug in stub fixed (could have been issues if return value used).
- Versions: cFS Bundle + this commit
CodeQL warning resolution
None
=> Fix #777, Static allocation of DummyVec in OSC_INUM_TO_IVEC stub

src/os/portable/os-impl-no-symtab.c
Fix #797 - updates os-impl-no-symtab.c to match latest APIs
Builds.
Now can build without dynamic loader (OSAL_CONFIG_INCLUDE_DYNAMIC_LOADER FALSE)
None
None
=> Fix #797, Update os-impl-no-symtab.c to match APIs

src/os/portable/os-impl-no-sockets.c
Fix #796 - updates os-impl-no-sockets.c to match latest APIs
Builds.
Now can build without network (OSAL_CONFIG_INCLUDE_NETWORK FALSE)
None
None
=> Fix #796, Update os-impl-no-sockets.c to match APIs

src/os/portable/os-impl-no-sockets.c, src/os/shared/src/osapi-binsem.c, src/os/shared/src/osapi-countsem.c, src/os/shared/src/osapi-errors.c, src/os/shared/src/osapi-file.c, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-module.c, src/os/shared/src/osapi-mutex.c, src/os/shared/src/osapi-queue.c, src/os/shared/src/osapi-sockets.c, src/os/shared/src/osapi-time.c, src/os/shared/src/osapi-timebase.c, src/os/vxworks/src/os-impl-symtab.c, src/ut-stubs/osapi-utstub-binsem.c, src/ut-stubs/osapi-utstub-countsem.c, src/ut-stubs/osapi-utstub-filesys.c, src/ut-stubs/osapi-utstub-mutex.c, src/ut-stubs/osapi-utstub-queue.c, src/ut-stubs/osapi-utstub-sockets.c, src/ut-stubs/osapi-utstub-task.c, src/ut-stubs/osapi-utstub-timebase.c
Fix #805 - fixed a couple missing null terminations and applied the general pattern (sizeof where it works)
Build and execute unit tests
Avoid missing null termination issues, no longer truncating filename in OS_ModuleInfo (src/os/shared/src/osapi-module.c)
None
None
=> Fix #805, Null terminate when using strncpy

src/tests/queue-test/queue-test.c
Using `%u` conversion requires an `unsigned int` arg, not `uint32` (it matches on some platforms, not on others).
Fixes #809
Build and run tests on RTEMS 4.11.3.
No more format mismatch warning/error.
RTEMS 4.11.3 QEMU target on Ubuntu 20.04 build host
=> Fix #809, cast args to printf in queue-test

src/os/shared/inc/os-shared-common.h, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-sockets.c, src/os/vxworks/src/os-impl-shell.c, src/os/vxworks/src/os-impl-symtab.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
Create a wrapper around `memchr()` that mimics the non-C99 function `strnlen()` which is defined in POSIX-2008.
Use this instead of `strlen()` whenever the string being checked either originates in or will be copied into a fixed-length array buffer.
Fixes #808 
Run all unit tests on both native and RTEMS
No behavior changes except if a bug causes strings to be unterminated.
RTEMS 4.11.3 (qemu)
Worth noting that in most cases this was testing the length of a string in the internal OSAL table entry, which was already length-checked when created.  So this check is somewhat redundant, the only way this could catch …
=> Fix #808, length-limited string length checks

src/tests/network-api-test/network-api-test.c, src/tests/select-test/select-test.c
Fixes #798 
Fixes #799
made the tests skip after getting their first not implemented error. 
Ubuntu 20.04
=> Fix #798 and #799, tests fail when no network

src/ut-stubs/osapi-utstub-file.c
Fix #814 - Updates stub helpers to match the behavior of calling the default implementation stub macro (NULL va list)
Build/execute unit tests, passed
None
None
None
=> Fix #814, UT Stub match macro behavior

src/os/vxworks/src/os-impl-network.c, src/os/vxworks/src/os-impl-timebase.c
Fix #819 - removes redundant logic (static analysis warnings)
None
- Versions: cFS bundle main + this commit
None
None
=> Fix #819, Remove redundant logic

src/os/shared/src/osapi-sockets.c
Fix #817 - just truncating at the end for socket name (not possibly 3 different locations)
Built and executed unit tests, passed
Will just truncate socket name at the end
Note coverage test isn't doing full branch coverage, still getting full line coverage.  Branch coverage is an existing issue.
None
Jacob Hageman - NASA
=> Fix #817, Simplify name truncation in OS_CreateSocketName

src/tests/bin-sem-test/bin-sem-test.c, src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c, src/tests/queue-test/queue-test.c
Fixes #779 
Rename global timer_id to local_timer_Id
Ubuntu 20.04
=> Fix #779, Change global vars to not be hidden by local vars.

ut_assert/inc/utstubs.h, ut_assert/src/utstubs.c
Fix #737 - renames UT_Stub_CheckForceFail to UT_Stub_CheckDefaultReturnValue, also only sets Value if not NULL (can pass in NULL value doesn't matter)
Build and execute unit tests (with corresponding nasa/cFE#1173)
None, name change
- Versions: cFS Bundle main + nasa/cFE#1173 + this commit
None
None
=> Fix #737, UT_Stub_CheckForceFail -> UT_Stub_CheckDefaultReturnValue

src/os/inc/osapi-file.h, src/os/shared/src/osapi-file.c, src/tests/file-api-test/file-api-test.c
Fix #833 - Initializes the file descriptor (output parameter) for all cases in OS_OpenCreate
Avoids various "possible uninitialized variable" warnings for routines that utilize this API.
Avoids static analysis warning, output never unset.
- Hardware: cFS Lab 5
- OS: CentOS 7
nasa/cFE#1185
None
=> Fix #833, Initialize file descriptor in OS_OpenCreate

ut_assert/src/uttools.c
Fixes #780
adds restriction check to file open.  
Ubuntu 20.04
=> Fix #780, restrict permissions on file create

src/tests/select-test/select-test.c
Fixes #828
Change the comment style 
Ubuntu 20.04
=> Fix #828, fix comment style

CMakeLists.txt, src/os/inc/osapi-version.h, src/os/shared/src/osapi-version.c, src/unit-test-coverage/shared/CMakeLists.txt, src/unit-test-coverage/shared/src/coveragetest-version.c, src/ut-stubs/CMakeLists.txt, src/ut-stubs/osapi-utstub-version.c
Adds 3 simple API calls:
const char *OS_GetVersion(void);
const char *OS_GetVersionCodeName(void);
const char *OS_GetVersionDescription(void);
These directly return the values of string macros defined in `osapi-version.h`.
The accessor function should be the preferred way to get the OSAL version string (vs. using macro directly) as it is evaluated at OSAL library compile time, rather than application compile time, and thus will remain correct in the event that OSAL is relinked without recompiling the application.
Fixes #821 
Build and run all unit tests, sanity check CFE.
This adds _new_ APIs to get version strings - does not change anything existing within OSAL.
Ubuntu 20.04 …
=> Fix #821, add accessor functions for version strings

SECURITY.md
Fix #836 
Updated the Security Policy to include the type of testing done for OSAL or the cFS bundle under a new section titled "Testing". Provided a disclaimer that under the Apache license, liability is not provided. 
Added that security reports should be emailed. 
Users should now be aware of the type of testing OSAL or the cFS bundle undergoes. 
References: 
https://github.com/thanos-io/thanos/security/policy
https://github.com/phpMussel/phpMussel/security/policy
https://github.com/timberio/vector/security/policy
=> Fix #836, Add Testing Tools to the Security Policy

src/os/shared/src/osapi-file.c
Fix #875 - move copyblock size to a `#define` and add comments
Build and run unit tests, passed
None
None
None
=> Fix #875, Move copyblock size to define

src/os/shared/src/osapi-common.c
Fix #873 - removed rogue while loop
CI
None
None
None
=> Fix #873, Remove rogue while loop in OS_DeleteAllObjects

src/os/portable/os-impl-bsd-sockets.c
Fix #859 - consolidates the duplicated switch in OS_SocketOpen_Impl
Build/execute unit tests, passed
None
None
None
=> Fix #859, Consolidate duplicated switch in OS_SocketOpen_Impl

src/os/portable/os-impl-bsd-select.c, src/os/shared/inc/os-shared-idmap.h, src/os/shared/src/osapi-idmap.c
Fix #854 - const input pointers for OS_FdSet_ConvertIn_Impl and OS_ObjectIdTransactionFinish
Build/execute unit tests, passed
None
None
None
Jacob Hageman - NASA/GSFC, OSAL code review
=> Fix #854, Const correct input pointers

src/os/inc/osapi-sockets.h
Fix #851 - removed network prototypes defined in `osapi_sockets.h` that are also in `osapi_network.h`
Build/execute unit tests, passed
None
None
None
=> Fix #851, Remove duplicate network prototypes

src/os/inc/common_types.h
Fix #842 - removes NULL redefine from common_types.h
Note: identified in OSAL code review and as implemented it was **always** defining NULL
None
None
None
=> Fix #842, Remove NULL redefine

CONTRIBUTING.md
Fix #911 
Added a contributing guide that links to the main cFS contributing guide. 
Users should be able to view the contributing guide contents easily from the OSAL repo. 
=> Fix #911, Add Contributing Guide

src/tests/file-api-test/file-api-test.c, src/tests/network-api-test/network-api-test.c, src/tests/select-test/select-test.c, src/tests/symbol-api-test/symbol-api-test.c, ut_assert/inc/utassert.h
Fixes  #752
Create new macro UtAssert_NA to use instead of UtPrintf to report cases when not implemented
Ubuntu 20.04
This is a redo of #816 which was closed because it was going to be part of #787 but that won't be done in the near future so this task is back as its own pull request. 
=> Fix #752, Utilize UTASSERT_CASETYPE_NA to report OS_ERR_NOT_IMPLEMENTED

src/os/portable/os-impl-bsd-select.c, src/unit-test-coverage/portable/adaptors/inc/ut-adaptor-portable-posix-io.h, src/unit-test-coverage/portable/adaptors/src/ut-adaptor-portable-posix-io.c, src/unit-test-coverage/portable/src/coveragetest-bsd-select.c, src/unit-test-coverage/ut-stubs/inc/OCS_sys_select.h, src/unit-test-coverage/ut-stubs/override_inc/sys/select.h
The `select()` implementation utilizes its own set size limit that should be checked.
Fixes #855
Build and run all unit tests, confirm coverage of select is testing new branches/returns.
Calls to OS_SelectSingle/OS_SelectMultiple will fail if an FD within the set is outside the range of the underlying `FD_SETSIZE` from the C library.
Ubuntu 20.04
Unfortunately this is a limitation/problem of the `select()` API - valid file handles may be effectively un-selectable due simply to the fact that `FD_SETSIZE` may be lower than the maximum number of open file descriptors.
The only alternative is to use `poll()` instead which uses a different API that does not have this …
=> Fix #855, check against FD_SETSIZE in bsd-select

src/os/portable/os-impl-bsd-select.c, src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
When calculating the relative time interval for the select() call, the increment should have been a decrement.
This also adds a UT case that specifically exercises the carryover described.
Fixes #857
Run test case specifically targeting this carry condition, confirm calculation result is correct now (400ms rather than 2.4s)
No extra delay when this carry condition is hit
Ubuntu 20.04
This just fixes the current calculation - but a better fix would be to use the interval logic now in `osapi-clock.h` (this wasn't available when this code was initially implemented).  Should do a follow-on issue to look into this for next version.
**Contributor Info - All …
=> Fix #857, correct interval calculation in DoSelect

src/os/portable/os-impl-bsd-sockets.c
A select() is used after connect() to provide application-controlled timeout on the connection initiation.
This just adds some comments to describe why this is done.  It also adds a debug statement if the connect fails for a reason other than `EINPROGRESS`.
Fixes #862
Build and sanity test, run unit tests
This does add one more OS_DEBUG statement for an unexpected error.  No impact to normal behavior.  
Ubuntu 20.04
=> Fix #862, comments describing select after connect

src/os/portable/os-impl-bsd-select.c
This is documented as a possible errno from select on some systems, and the call should be repeated in that case.
Fixes #858 
Build and sanity check, run unit tests
None
Ubuntu 20.04
=> Fix #858, add check for EAGAIN in addition to EINTR

src/os/portable/os-impl-bsd-sockets.c
OSAL provides an abstract buffer for socket addresses, independent of the underlying implementation.  The size of this buffer is
configurable by the user via compile-time options.
This adds a CompileTimeAssert to confirm that the size of this abstract buffer is large enough to store any of the enabled
address types. This also removes the need for runtime tests.
Fixes #861
Build and sanity test, run unit tests
This change means that the `OS_SOCKADDR_MAX_LEN`  __must__ be configured large enough for all enabled address types.  For instance, ipv6 addresses are likely to be larger than ipv4 addresses in the implementation.  It is therefore possible to se OS_SOCKADDR_MAX_LEN large enough for ipv4 but not large …
=> Fix #861, compile time assert for sockaddr size

src/tests/shell-test/shell-test.c
Fixes #416
Adds functional test for shell commands
Ubuntu 20.04
=> Fix #416, add shell functional test

src/os/portable/os-impl-posix-io.c, src/unit-test-coverage/portable/src/coveragetest-posix-io.c
The ESPIPE errno means that seeking is not supported on the given file handle.  Translate to the `OS_ERR_OPERATION_NOT_SUPPORTED` error rather than not implemented as it better indicates the actual condition.
Fixes #867
Build and sanity check, run tests
Better error code if attempting to seek on a pipe/socket
Ubuntu 20.04
=> Fix #867, better error translation for ESPIPE errno

src/os/posix/src/os-impl-console.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/os/rtems/src/os-impl-timebase.c, src/os/shared/inc/os-shared-globaldefs.h
The "U32" designation in the name had become confusing because all the members had over time migrated to a separate non-uint32/dedicated type.
The point is to pass a value through a void* so a name change better indicates that purpose.
Also adds a compile time assert to this intent - this wrapper may only be used to directly pass values which have a size less than or equal to `sizeof(void*)` -- if anything is bigger than this it will not work.
Fixes #869 
Build and run all tests, sanity check
None
Ubuntu 20.04
=> Fix #869, rename OS_U32ValueWrapper_t

src/os/shared/src/osapi-filesys.c
The return statement from OS_FileSys_FindVirtMountPoint() was performing several match operations and was hard to understand.
This breaks up the statement so it is easier to read and adds some informational comments.
Fixes #876 
None - actual logic is the same.
Ubuntu 20.04
=> Fix #876, break up logic in return statement

src/os/vxworks/src/os-impl-timebase.c, src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
In VxWorks the impl calls timer_settime followed by timer_gettime on the same timer to check if rounding occurred.  If the second call fails this reports it as an error.
Note unless there is some sort of OS bug this should be impossible to happen as this code only runs after a successful timer_settime.
Fixes #889
Build and sanity check, run unit tests
A failure to call timer_gettime after timer_settime is reported as an error.
Ubuntu 20.04
=> Fix #889, report timer_gettime error

src/os/vxworks/src/os-impl-loader.c, src/unit-test-coverage/vxworks/src/coveragetest-loader.c
Propagate a VxWorks error on moduleInfoGet() call into OS_ERROR return.
Fixes #886
Build and sanity check, run unit tests
Error on moduleInfoGet() gets returned to caller as OS_ERROR status.
Ubuntu 20.04
=> Fix #886, return moduleInfoGet error

src/os/shared/src/osapi-module.c
In the current implementation, the same patterns apply to modules as the rest of the OSAL services.  
Fixes #882
Build and run tests
None - comment only
Ubuntu 20.04
In a previous version there as a special case for 0 modules but this is no longer true, and the comment had become outdated.
=> Fix #882, make module comment same as other services

src/os/shared/src/osapi-mutex.c
The only way for this test happen would be if somehow the normal unlock process was bypassed, such that the underlying OS mutex was unlocked but OSAL state still had it owned by a task.  Removing as extraneous/unneeded.
Fixes #883 
Build and run CFE, run unit tests
None.  This condition never happens at runtime, and only a debug statement if it did.
Ubuntu 20.04
As noted, it is not _entirely_ unreachable in all circumstances - if there was some sort of bug that cause the wrong mutex to get released and/or otherwise throw off OSAL state, this debug message would tell you that it happened.  But outside of a bug somewhere, this really should never happen.... …
=> Fix #883, remove unreachable test

src/os/portable/os-impl-bsd-select.c
Add an extra limit check for the index, as it is possible due to padding that this goes beyond the end of the array.
Fixes #919 
Validate all coverage tests now pass
None
Ubuntu 20.04
Should fix the issue seen in integration candidate #917 
=> Fix #919, check index inside fdset conversions

src/os/portable/os-impl-bsd-select.c, src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
Fix #921
Do not silently ignore a filehandle which was included in the `OS_FdSet` but the "selectable" flag is false.  Instead translate this to the `OS_ERR_OPERATION_NOT_SUPPORTED` error.
Run unit tests on native and RTEMS and make sure all passing
Passing a filehandle into `OS_SelectMultiple()` (via the OS_FdSet) for which the RTOS does not implement select() should return the 
OS_ERR_OPERATION_NOT_SUPPORTED error (again)
Ubuntu 20.04 (native) and RTEMS 4.11.3 (cross)
This is old behavior but was masked by the fact that OS_SelectMultiple_Impl() actually returned the same error - OS_ERR_OPERATION_NOT_SUPPORTED - for an _empty_ set as it did if one passed a …
=> Fix #921, make non-selectable FD an error

src/os/portable/os-impl-bsd-sockets.c, src/unit-test-coverage/portable/adaptors/inc/ut-adaptor-portable-posix-io.h, src/unit-test-coverage/portable/adaptors/src/ut-adaptor-portable-posix-io.c, src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
The fcntl() function is documented as returning -1 on error, so test for this condition and report errno if so.  There is no
recourse/handling - this just reports the error.
However - failure to set the O_NONBLOCK flag via this method will fall back to blocking mode being used (timeouts will not
work as a result).
Fixes #863
Build and sanity check, run unit tests, check coverage
if setting O_NONBLOCK fails, then debug message is printed and blocking mode is used.
Ubuntu 20.04
No real recourse in code - this shouldn't fail, but if it does, errno is printed so user can diagnose why it failed.
**Contributor Info - All information REQUIRED for consideration of pull …
=> Fix #863, check/report fcntl status

src/os/inc/common_types.h
The "common_types.h" file will no longer provide these as they are not needed by OSAL and do not/cannot handle all cases.
Fixes #843
Build and sanity check CFE, run all unit tests
Application code with endianness dependency that was relying on these symbols may break (it should be fixed).
Ubuntu 20.04
Needs nasa/cfe#1218 in order to not break the CFE build.
=> Fix #843, remove BIG/LITTLE bit order macros

src/os/inc/osapi-dir.h, src/os/inc/osapi-select.h, src/os/inc/osapi-task.h, src/os/portable/os-impl-bsd-select.c, src/os/portable/os-impl-posix-dirs.c, src/os/shared/src/osapi-common.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-printf.c, src/os/shared/src/osapi-queue.c, src/os/shared/src/osapi-select.c, src/os/vxworks/src/os-impl-console.c, src/os/vxworks/src/os-impl-tasks.c, src/os/vxworks/src/os-impl-timebase.c
Fix #846, Minor cleanup detailed in #846 identified during code review
Build/run unit tests
None
None
None
=> Fix #846, Minor clean up and clarification in comments/naming

src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c, src/unit-test-coverage/ut-stubs/src/arpa-inet-stubs.c, src/unit-test-coverage/ut-stubs/src/osapi-select-impl-stubs.c, src/unit-test-coverage/ut-stubs/src/sys-socket-stubs.c
Fix #831 - adds test to get full coverage of os-impl-bsd-socket.c
Built/run unit tests, pass
Full line coverage of os-impl-bsd-socket.c for OSAL
None
None
Ping @ejtimmon - example for stubs/hooks/etc
=> Fix #831, Finish os-impl-bsd-socket.c coverage testing

src/os/inc/osapi-error.h, src/os/vxworks/src/os-impl-symtab.c, src/unit-test-coverage/vxworks/adaptors/inc/ut-adaptor-symtab.h, src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-symtab.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
Improve the error codes from this function.
- Introduces a new error `OS_ERR_OUTPUT_TOO_LARGE` if the size limit was insufficient (instead of `OS_SUCCESS`).
- Return `OS_ERROR` if an empty file was written - this likely indicates some fundamental issue with the VxWorks symbol table.
- Return `OS_ERR_NAME_TOO_LONG` if one of the symbol names was too long, (instead of generic `OS_ERROR`).
Improve unit test to check for/verify these responses.
Fixes #888
Build and sanity check, run all unit tests, confirm coverage of new cases.
Better/more descriptive return codes if OS_SymbolTableDump_Impl does not do what is expected.
Ubuntu 20.04 …
=> Fix #888, better return codes from OS_SymbolTableDump_Impl

src/examples/tasking-example/tasking-example.c, src/os/inc/osapi-task.h, src/os/shared/inc/os-shared-task.h, src/os/shared/src/osapi-task.c, src/tests/bin-sem-flush-test/bin-sem-flush-test.c, src/tests/bin-sem-test/bin-sem-test.c, src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c, src/tests/count-sem-test/count-sem-test.c, src/tests/mutex-test/mutex-test.c, src/tests/osal-core-test/osal-core-test.c, src/tests/queue-test/queue-test.c, src/tests/sem-speed-test/sem-speed-test.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/oscore-test/ut_oscore_test.c, src/ut-stubs/osapi-utstub-task.c
The `OS_TaskRegister()` function is no longer needed and has been a no-op since v5.0.0.
This removes the function and all references to it in code, tests, and documentation.
Fixes #853 
Build and sanity check CFE, run all unit tests
No impact to behavior, but does affect API and has depenedencies
Ubuntu 20.04
Function removal affects API - Needs to be merged with nasa/cfe#1250.
=> Fix #853, remove OS_TaskRegister

src/tests/CMakeLists.txt
Fix #934, Removes the flag defined in tests/CMakeLists.txt that isn't used anywhere
None
None
None
=> Fix #934, Remove unused SCRIPT_MODE flag

src/tests/file-api-test/file-api-test.c
Do not initialize or compare osal_id_t directly to integers, use the provided comparison function.
Fixes #929
System builds and runs again when using a type-safe/non-integer osal_id_t type.
Ubuntu 20.04
=> Fix #929, use test function for osal_id_t

src/os/portable/os-impl-posix-gettime.c, src/os/posix/inc/os-impl-gettime.h, src/os/rtems/inc/os-impl-gettime.h, src/os/vxworks/inc/os-impl-gettime.h
The portable clock_gettime implementation had been using CLOCK_MONOTONIC to support its use as a PSP timebase for some platforms that used it this way.  However with updates on the PSP side this is not required anymore.
Preference should be to use CLOCK_REALTIME as it better aligns with the described semantics of the OSAL clock function, and makes for a better default.  This can still be easily changed back if the user desires.
Fixes #844
Build and sanity check CFE, run all unit tests
OS_GetLocalTime() and OS_SetLocalTime() will work as described.  
Ubuntu 20.04
This depends on _not_ using the OSAL clock as a monotonic timebase.  nasa/psp#285 is required to fix …
=> Fix #844, switch to use CLOCK_REALTIME

src/os/vxworks/src/os-impl-shell.c
Rather than using a default name, use a specific name so that it can be polled more safely.
Fixes #887
Build and run coverage tests
Also enable shell and run "shell-test" on MCP750
No longer using a string pointer which may be invalid.
MCP750, vxworks 6.9
Although this while loop seems to be working OK, the overall "shell-test" actually fails on the MCP750 because it looks like the shell does not have an "echo" function.  This seems to be a separate issue, not sure if/how this test ever worked.
=> Fix #887, specify shell name in ShellOutputToFile

src/os/posix/src/os-impl-console.c, src/os/rtems/src/os-impl-console.c, src/os/shared/inc/os-shared-common.h, src/os/shared/src/osapi-common.c, src/os/shared/src/osapi-idmap.c, src/os/shared/src/osapi-printf.c, src/os/vxworks/src/os-impl-console.c, src/unit-test-coverage/shared/src/coveragetest-common.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c, src/unit-test-coverage/shared/src/coveragetest-printf.c
Replaces the separate "Initialized" and "Shutdown" flags with a single state flag.  This simplifies things and makes for a single source of truth for the state of OSAL globally.
Note this is not strictly necessary, but it will likely be required if the intent is to be able to run tests (and OS_API_Init()) multiple times without a reboot in the middle to reset the state.
Fixes #871 
Fixes #691 
- Multiple invocations of `OS_API_Init()` are allowed - subsequent calls can be ignored
- Deleting of any internal objects that did get created if `OS_API_Init()` fails (this leaves system in same state as when it started)
- Allows Re-initialization of OSAL after …
=> Fix #871, allow OSAL re-initialization

src/os/inc/osapi-common.h, src/os/shared/src/osapi-common.c, src/tests/bin-sem-flush-test/bin-sem-flush-test.c, src/tests/bin-sem-test/bin-sem-test.c, src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c, src/tests/count-sem-test/count-sem-test.c, src/tests/file-api-test/file-api-test.c, src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c, src/tests/idmap-api-test/idmap-api-test.c, src/tests/mutex-test/mutex-test.c, src/tests/network-api-test/network-api-test.c, src/tests/osal-core-test/osal-core-test.c, src/tests/queue-test/queue-test.c, src/tests/select-test/select-test.c, src/tests/sem-speed-test/sem-speed-test.c, src/tests/shell-test/shell-test.c, src/tests/symbol-api-test/symbol-api-test.c, src/tests/time-base-api-test/time-base-api-test.c, src/tests/timer-add-api-test/timer-add-api-test.c, src/tests/timer-test/timer-test.c, src/unit-test-coverage/shared/src/coveragetest-common.c, src/unit-tests/oscore-test/ut_oscore_test.c, src/unit-tests/osfile-test/ut_osfile_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_test.c, src/unit-tests/osloader-test/ut_osloader_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.c
This cleans up all OSAL resources as best as possible, ideally leaving the system in a state where OS_API_Init() may be invoked again.
Fixes #944
Fixes #197 
Build and run all unit tests, confirm correct behavior
Test in conjunction with fix for #197, confirm test can be run multiple times on VxWorks without reboot
Adds OS_API_Teardown API to complement OS_API_Init
MCP750 vxworks 6.9
=> Fix #944, add OS_API_Teardown

src/tests/shell-test/shell-test.c
The shell may add extra output beyond the intended content, but the shell-test was only looking for exact match.  Extra output may include whitespace and/or an echo of the command itself.
This reworks the shell test to allow for this extra output, as long as the intended string appears in the content of the file it will
pass.
Fixes #939
Build and run the shell test
Note this requires modifying the osal config to enable shell, otherwise test is skipped.
Test passes.
Ubuntu 20.04 (native, posix)
MCP750 vworks6.9
Not clear how this test ever worked... maybe different versions of VxWorks work differently here.  But this approach should (hopefully) be a little more …
=> Fix #939, rework shell test

src/os/inc/osapi-file.h, src/os/portable/os-impl-posix-files.c, src/os/portable/os-impl-posix-gettime.c, src/os/shared/inc/os-shared-file.h, src/os/shared/src/osapi-file.c, src/unit-test-coverage/portable/src/coveragetest-posix-files.c, src/unit-test-coverage/shared/src/coveragetest-file.c, src/unit-test-coverage/ut-stubs/src/osapi-file-impl-stubs.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/ut-stubs/osapi-utstub-file.c
Fix #932 - changed parameter names to avoid collisions
None
- Hardware: Local docker container
None
None
=> Fix #932, Eliminate time and access name collisions with VxWorks

src/os/inc/osapi-file.h
Update the API documentation for OS_read/write/TimedRead/TimedWrite. Clarify that zero will be returned on EOF condition, and in the case of the timed API calls, the OS_ERR_TIMEOUT status code will be returned if the timeout expired without the handle becoming readable/writable during that time.
This is intended behavior such that it allows the caller to differentiate between a handle which is in a state where it cannot read/write any more data (e.g. at EOF, or a pipe/socket with remote end closed) and a handle which is simply idle or busy.
Fixes #970 
Build and sanity check, run all tests
None - documentation update only
Ubuntu 20.04 …
=> Fix #970, update documentation for read/write

.github/workflows/codeql-build.yml, .github/workflows/local_unit_test.yml, .gitignore, Makefile.sample, src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
Fix #419 - Adds local makefile (trivial single build sample, can use different build directories for multiple platform)
Fix #729 - Adds bundle and local unit test run and coverage verification
Fix #954 - Added missing line coverage
Self testing!  Also checked distclean and install independently.
Runs the unit tests again, both from the context of the bundle config and local OSAL config.  Verifies 100% line coverage.
- Hardware: Local docker container
- Versions: cFS Bundle main + these commits
None
None
=> Fix #419 #729 #954, Adds local makefile and bundle/local unit test actions with coverage verification

src/os/shared/src/osapi-sockets.c, src/tests/network-api-test/network-api-test.c
This improves the network-api-test to do multiple connections, re-using the same acceptor socket between them.
As reported in #969, the OS_SocketAccept call was using the incorrect token, using the server/acceptor socket when it should have used the connection socket.
The bug overwrote data in the acceptor socket, but it would only cause an issue when the user attempted to use the server socket to accept a second connection, but the tests only performed a single connection.
With the improvement to network-api-test to run multiple connections, it now reveals the bug in the test.  Without the fix, the test failed on the second connection.  With the fix to OS_SocketAccept to use the correct token, the test passes fine again.
Fixes #969  …
=> Fix #969, socket accept using incorrect record

ut_assert/src/uttools.c
Fix the UtPrintx() routine such that the loop stops correctly.  Also improves the output to print the address, not just the data.
Note if UtPrintf is used, one sees the file/line of the UtPrintx function, not the actual test location, so it is better to call
UT_BSP_DoText directly so it omits this extraneous info.
Fixes #964 
Temporarily Update a test to use UtPrintx() -- this function was not used in any current tests -- and confirm that the output now works as expected.
No infinite loop in UtPrintx, and also it now includes the memory address of the data, not just the data itself.
Ubuntu 20.04
Joseph …
=> Fix #964, UtPrintx function

doc/OSAL-Configuration-Guide.md
Significant update to the configuration guide for the current build system (CMake) and the currently provided set of OS/BSP layers.  Many of the examples in this guide referred to items which are now obsolete.
However, this does *NOT* fix references to the applications and in particular the "tasking example" as this still may be brought back.
Fixes #640 
View guide in markdown viewer, confirm commands/pathnames in guide seem to match current version
None - documentation only
Commands in document were validated on Linux and RTEMS where possible
=> Fix #640, configuration guide updates

src/os/inc/osapi-task.h
Clarify use of the stack_size parameter, and that it should not be 0.
Fixes #545 
Build and sanity check, run all unit tests
None, documentation update only
Ubuntu 20.04
Other items listed in #545 are fixed by PR #972
=> Fix #545, update OS_TaskCreate doc

src/os/portable/os-impl-bsd-sockets.c, src/os/posix/inc/os-impl-sockets.h, src/os/rtems/inc/os-impl-sockets.h, src/os/vxworks/inc/os-impl-sockets.h, src/tests/network-api-test/network-api-test.c, src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
In some versions of VxWorks the fcntl F_GETFL/F_SETFL opcodes do not appear to be implemented, and thus it is not possible
to set O_NONBLOCK mode.  However, this mode is not necessarily required, it is more of a backup/failsafe.
The "selectable" flag should not be dependent on whether O_NONBLOCK flag got set.
This also adjust some timeouts and adds some delays to improve the reliability of network-api-test on VxWorks.  The timeouts
were only 10ms, and this is much too short as messages are getting written on a 9600 baud console (avg 1ms/char).  A single log message can easily take 50-60ms alone.
Fixes #988 
Execute network-api-test on supported platforms (esp. VxWorks 6.9 in particular)
Test now passes …
=> Fix #988, do not require nonblock mode

src/os/shared/src/osapi-dir.c
The status code from the low level implementation needs to be returned from the caller, in case it was not OS_SUCCESS.
Fixes #999 
Build and sanity check CFE, run all tests
The status returned from `OS_rmdir()` should now be correct if the implementation failed.
Ubuntu 20.04
=> Fix #999, propagate status code in OS_rmdir

ut_assert/src/utbsp.c
If messages (e.g. from UtPrintf, etc) already have a newline, do not add another.
Fixes #1002
Build and run OSAL unit tests
Extra blank lines in test log are removed.
Ubuntu 20.04
This should preserve extra newlines in the event that the test case was intentionally adding whitespace, by only appending one if it was _not_ there to begin with.
=> Fix #1002, remove extra newlines in utassert logs

src/unit-tests/inc/ut_os_support.h, src/unit-tests/oscore-test/ut_oscore_binsem_test.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/oscore-test/ut_oscore_mutex_test.c, src/unit-tests/oscore-test/ut_oscore_queue_test.c, src/unit-tests/oscore-test/ut_oscore_select_test.c, src/unit-tests/oscore-test/ut_oscore_select_test.h, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/oscore-test/ut_oscore_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Update most of the conditions in the "unit tests" to use the support macros whenever possible.  The macros display the
function being called as well as the return value being checked for, and therefore this makes it so the test log file can be
cross referenced back to the documentation to ensure the documented return codes are being tested.
As a nice side effect this also removes quite a bit of repetition in the test programs.
Fixes #981
Build and run all OSAL unit tests
Log file produced has much more detail, and can now be cross referenced back to documentation.
RTEMS 4.11 (pc686+qemu)
See gist of complete test output log for …
=> Fix #981, rework "unit-tests" to use macros

src/tests/file-api-test/file-api-test.c, src/unit-test-coverage/shared/src/coveragetest-dir.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c
Fixes #994
Changed tests to use valid inputs for all OS_mkdir calls. 
Ubuntu 20.04
=> Fix #994, fixed invalid inputs for OS_mkdir

.github/workflows/codeql-osal-default.yml
Fix #986 
Checkout just the osal repository rather than the entire cFS bundle to allow CodeQL to provide a code preview. 
Code preview is not available when the entire cFS bundle is checked out. The osal itself must be the only repository checked out. 
Since the tests require the cFE repo, they are removed.  
Tested locally on forked repository 
Tested on this PR. Example of code scanning result found here: https://github.com/nasa/osal/security/code-scanning/142?query=ref%3Arefs%2Fpull%2F987%2Fmerge
Code preview should be available in the osal repository. 
Tests are not used. 
=> Fix #986, Show CodeQL Preview

src/tests/count-sem-timeout-test/count-sem-timeout-test.c
Fixes #991
Adds count semaphore timeout test
Adds about 8 seconds to unit tests. 
Ubuntu 20.04
=> Fix #991, Add count sem timeout test

CMakeLists.txt, doc/src/CMakeLists.txt, doc/src/osal-apiguide.doxyfile.in, doc/src/osal-common.doxyfile.in, doc/src/osal_fs.dox, doc/src/osal_timer.dox, doc/src/osalmain.dox
Add the "doxyfile" templates and various OSAL doxygen pages locally under the "doc/src" directory.  Add a CMake script
to build the documentation in either a standalone or integrated build environment.
Fix #913 
Build OSAL "api guide" documentation in a standalone build environment, confirm output works and matches what is generated from the CFE build.
Able to build OSAL API Guide in a standalone environment, independently of CFE build.
Ubuntu
If this is merged, then a logical follow on would be to remove the same templates and dox files from CFE tree and have the CFE documentation call this script to build the OSAL API guide.
**Contributor Info - All …
=> Fix #913, include doxygen targets locally

src/os/shared/src/osapi-idmap.c
Fix #984 - Updates the public nature of OS_ObjectIdToArrayIndex and related documentation
CI, documentation only 
None, documentation
CI
None
None
=> Fix #984, Document OS_ObjectIdToArrayIndex as public

src/os/inc/osapi-binsem.h
Ensures correlation between the unit-tests and documented return values for the OSAL binsem API.
Fixes #1008
Ubuntu
=> Fix #1008, resolve discrepancies between binsem API and unit tests

src/os/inc/osapi-clock.h, src/unit-tests/oscore-test/ut_oscore_misc_test.c
Corrects unit test retval discrepancies in clock code
Note that the success case for OS_SetLocalTime is tested, but is marked as a MIR test case because it requires
elevated permission, it is expected to fail when running as a normal user on Linux.
Fixes #1009 
Run all unit tests, confirm documented return values are checked, and checked return values are documented.
No change to FSW, test/doc only
Ubuntu
=> Fix #1009, add missing clock retcode tests

src/os/inc/osapi-countsem.h
Ensures correlation between the unit-tests and documented return values for the OSAL countsem API.
Fixes #1011
Ubuntu
=> Fix #1011, resolve discrepancies between countsem API and unit tests

src/os/inc/osapi-module.h, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c
Ensures correlation between the unit-tests and documented return values for the OSAL module API.
Fixes #1016
Ubuntu
=> Fix #1016, resolve discrepancies between module API and unit tests

src/os/inc/osapi-mutex.h
Ensures correlation between the unit-tests and documented return values for the OSAL mutex API.
Fixes #1017
Ubuntu
=> Fix #1017, resolve discrepancies between mutex API and unit tests

src/os/inc/osapi-queue.h, src/unit-tests/oscore-test/ut_oscore_queue_test.c
Ensures correlation between the unit-tests and documented return values for the OSAL queue API.
Fixes #1018
Ubuntu
=> Fix #1018, resolve discrepancies between queue API and unit tests

src/os/inc/osapi-task.h, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/oscore-test/ut_oscore_task_test.h, src/unit-tests/oscore-test/ut_oscore_test.c
Ensures correlation between the unit-tests and documented return values for the OSAL task API.
Fixes #1021 
Ubuntu
=> Fix #1021, resolve discrepancies between task API and unit tests

src/os/inc/osapi-timebase.h, src/tests/time-base-api-test/time-base-api-test.c
Ensures correlation between the test cases and documented return values for the OSAL timebase API.
Fixes #1022 
Ubuntu
=> Fix #1022, resolve discrepancies between timebase API and unit tests

src/os/inc/osapi-heap.h, src/os/inc/osapi-network.h, src/os/inc/osapi-shell.h, src/unit-tests/inc/ut_os_support.h, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Correct missing doxygen retvals and other discrepancies between test and documentation
Note, other tests were OK, but depend on support being enabled and supported by RTOS.  Script will report N/A items (due to no impl) as missing.  Confirmed OS_HeapGetInfo() is OK on RTEMS.
Fixes #1024
Run unit tests, revalidate test log against documentation
No change to FSW, test/doc only
Ubuntu
RTEMS 4.11
=> Fix #1024, check misc API return codes

.github/workflows/codeql-cfe-build.yml
Fixes #1035 
Rename codeql-build.yml to codeql-cfe-build.yml for clarity of what the workflow does. Changed from CodeQL Analysis to CodeQL cFE Build as workflow name. 
Users can differentiate between this workflow and the osal default workflow.
Skip duplicate actions license: https://github.com/fkirc/skip-duplicate-actions/blob/master/LICENSE
=> Fix #1035, Rename CodeQL cFE Build and add Duplicate Job

src/ut-stubs/osapi-timebase-stubs.c, ut_assert/scripts/generate_stubs.pl
In the stub generator script, filter only whole words when ignoring keywords.  Do not match if the word appears as a substring inside a larger word.
Fixes #1048
Regenerate stubs, and build and run all unit tests.
Corrects the argument name in OS_TimeBaseCreate stub (only occurrence discovered so far)
Ubuntu
=> Fix #1048, filter only whole words for keyword match

.github/workflows/codeql-cfe-build.yml, .github/workflows/codeql-osal-default.yml
Fix #1025 
Created two configuration files, one for default queries and security queries and another for jpl rules. Waiting for https://github.com/nasa/osal/pull/1039 to be merged to add these queries in the newly created workflow, codeql-cfe-build.yml. 
Testing done on cFE forked repository, ArielSAdamsNASA/cFE which used the same files, but with different configuration paths.
Jobs were failing when the entire path of the configuration file were not used. Have to use nasa/cFE/.github/codeql/config-name@branch-name. The branch must be included in the path. 
The CodeQL analysis workflow will fail for this PR since it is calling for a configuration file in main the main branch. It will not work until the configuration files are merged into …
=> Fix #1025, Implement Coding Standard Rules in CodeQL

ut_assert/inc/utbsp.h, ut_assert/src/utassert.c, ut_assert/src/utbsp.c, ut_assert/src/uttest.c
Adding a mutex around modifications to globals allows UtAssert statements to be done from any test thread.
Fixes #1061
Build and run all unit tests, confirm correct operation
UtAssert statements can now be used from any test task without risk of interference
Ubuntu
Will require an update to CFE if accepted
=> Fix #1061, add mutex lock around UtAssert globals

src/os/inc/osapi-file.h, src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Ensures correlation between the test cases and documented return values for the OSAL file API.
Fixes #1013
Ubuntu
=> Fix #1013, resolve discrepancies between file API and unit tests

src/os/inc/osapi-filesys.h, src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c, src/unit-tests/osfilesys-test/ut_osfilesys_diskio_test.c
Ensures correlation between the test cases and documented return values for the OSAL filesys API.
Fixes #1014
Ubuntu
=> Fix #1014, resolve discrepancies between filesys API and unit tests

src/os/inc/osapi-idmap.h, src/os/shared/src/osapi-idmap.c, src/tests/idmap-api-test/idmap-api-test.c, src/tests/osal-core-test/osal-core-test.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c
Ensures correlation between the test cases and documented return values for the OSAL idmap API.
Fixes #1015
**NOTE:** This does update one return code from the the internal function `OS_ObjectIdTransactionInit`, changing it from OS_ERR_INCORRECT_OBJ_TYPE to OS_ERR_INVALID_ID.  There was one case in OS_GetResourceName where this status code gets eventually returned to an application caller, and OS_ERR_INVALID_ID makes it more consistent with other APIs in this regard.  (In other modules the idtype is hard coded so it does not affect these, this error …
=> Fix #1015, resolve discrepancies between idmap API and unit tests

src/os/inc/osapi-select.h, src/tests/select-test/select-test.c, src/unit-tests/oscore-test/ut_oscore_select_test.c
Ensures correlation between the test cases and documented return values for the OSAL select API.  This substantially overhauls the select-test to get better coverage of the various features.
Fixes #1019
Build and sanity check, run all unit tests, re-run cross reference script to confirm retcodes are exercised in the unit tests.
Better coverage of the various select API return codes in the tests.
Ubuntu
This does asserts in sub-tasks (preexisting condition) so rather than rewrite I suggest fixing #1061 to make it safer.
=> Fix #1019, resolve discrepancies between select API and unit tests

src/os/inc/osapi-sockets.h, src/os/portable/os-impl-bsd-sockets.c, src/tests/network-api-test/network-api-test.c, src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c
Ensures correlation between the test cases and documented return values for the OSAL socket API.
Fixes #1020
Ubuntu
=> Fix #1020, resolve discrepancies between socket API and unit tests

src/os/inc/osapi-select.h, src/os/shared/src/osapi-select.c, src/ut-stubs/osapi-select-stubs.c
This function does not modify its "Set" argument, therefore it should be qualified as "const".
Fixes #1062 
Build and sanity check, run all unit tests
None, just const correct API
Ubuntu
=> Fix #1062, const correct OS_SelectFdIsSet

src/os/inc/osapi-select.h
Fix usersguide doxygen warning for OS_SelectSingle and OS_SelectMultiple msecs input parameter.
No doxygen warning
See https://github.com/nasa/cFS/pull/265/checks?check_run_id=2798133902
None
=> HOTFIX:2021-06-15, Add missing OS_Select param doc

.github/workflows/build-osal-apiguide.yml
Fix #1036 Adding a workflow that will build the OSAL API Guide, and check that there are no errors or warnings. 
Currently, the warning-check job always finds warnings. Workflow will complete successfully once documentation warnings are fixed.
Marked as draft since it needs integration-candidate to be merged to main.
1. Pushed workflow file.
2. Verified workflow runs as expected.
A new workflow will run on every push and pull request.
- Tested on the Github servers where CI actions get to run. (Ubuntu 18.04)
Jose F. Martinez Pedraza/NASA GSFC
=> Fix #1036 Add Workflow to build and verify OSAL API Guide

doc/osal-detaildesign.doxyfile.in
This file indicates which input dirs to use for the cFE detail design document.  It should be controlled with OSAL, as this
knows the detail of the directory tree.
Fixes #1069 
Build cFE detail design document, confirm correct/expected content, with no duplicate "mainpage"
Detail design document has `src/os` and `src/bsp` content, but NOT the mainpage that is specific for the OSAL API guide.
Ubuntu
Related to nasa/cfe#1612
=> Fix #1069, add detail design template

src/ut-stubs/utstub-helpers.h
Fix #1074 - increases the UT object limit bits from 16 to 32
CI
None
CI
Fix for stakeholder
None
=> Fix #1074, Increase UT object limit for testing

src/os/inc/osapi-filesys.h, src/os/inc/osapi-network.h, src/os/inc/osapi-task.h, src/os/shared/src/osapi-filesys.c, src/os/shared/src/osapi-queue.c, src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c, src/tests/network-api-test/network-api-test.c, src/tests/time-base-api-test/time-base-api-test.c, src/tests/timer-add-api-test/timer-add-api-test.c, src/unit-test-coverage/shared/src/coveragetest-binsem.c, src/unit-test-coverage/shared/src/coveragetest-countsem.c, src/unit-test-coverage/shared/src/coveragetest-dir.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/shared/src/coveragetest-mutex.c, src/unit-test-coverage/shared/src/coveragetest-queue.c, src/unit-test-coverage/shared/src/coveragetest-task.c, src/unit-tests/oscore-test/ut_oscore_binsem_test.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c, src/unit-tests/oscore-test/ut_oscore_mutex_test.c, src/unit-tests/oscore-test/ut_oscore_queue_test.c, src/unit-tests/oscore-test/ut_oscore_select_test.c, src/unit-tests/oscore-test/ut_oscore_task_test.c, src/unit-tests/osfile-test/ut_osfile_dirio_test.c, src/unit-tests/osfile-test/ut_osfile_fileio_test.c, src/unit-tests/osloader-test/ut_osloader_module_test.c, src/unit-tests/osloader-test/ut_osloader_symtable_test.c, src/unit-tests/osnetwork-test/ut_osnetwork_misc_test.c, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
Another pass through the API to ensure that:
1. every function parameter marked "nonnull" in doxygen has an individual `OS_INVALID_POINTER` retcode test
2. every function parameter marked "nonzero" in doxygen has an individual `OS_ERR_INVALID_SIZE` retcode test
3. every function parameter accepting an `osal_id_t` type has two `OS_ERR_INVALID_ID` retcode tests, and that it is tested with `OS_OBJECT_ID_UNDEFINED` and `UT_OBJID_INCORRECT` (which is not zero, but not valid).
Run all unit tests, and run validation script on tests logs to confirm parameters have been exercised and confirmed for each required retcode.
Missing tests are implemented
Ubuntu
This PR will …
=> Fix #1052, implement missing parameter/retcode test permutations

src/unit-tests/oscore-test/ut_oscore_task_test.c
To account for potential of imprecise timing/clock sampling when running on a VM, allow for a wider range of time values to pass the test.
Fixes #1080 
Build and run tests using QEMU
Test now pass even if the time difference is not exactly the expected range.
RTEMS 4.11.3 under QEMU
=> Fix #1080, add range to OS_TaskDelay checks

src/os/rtems/src/os-impl-tasks.c
Ensures that OS_GetTaskId_Impl() returns OS_OBJECT_ID_UNDEFINED if called from the root task - as this does not have an OSAL task ID.
Fixes #1084
Run unit tests on RTEMS
Tests pass
RTEMS 4.11.3
=> Fix #1084, root task ID on RTEMS

src/unit-tests/osloader-test/ut_osloader_symtable_test.c
For the MCP750, the symbol table fairly large and requires a considerably larger limit to avoid the OS_ERR_OUTPUT_TOO_LARGE limit.  This also uses a different name, so that the user can actually see the symbol dump file if they want (otherwise the next test overwrites the file).
Fixes #1082
Run osal_loader_UT
Symbol table dump test now passes
=> Fix #1082, increase UT symbol dump size limit

src/os/vxworks/src/os-impl-timebase.c, src/unit-test-coverage/vxworks/src/coveragetest-timebase.c
Skip the registration of a timer in VxWorks when the assigned_signal is 0 (this indicates an external sync function is used).
Fixes #1087
Run time-base-api-test
Test now passes
=> Fix #1087, do not register RTOS timer for external sync

src/bsp/generic-vxworks/src/bsp_start.c, src/unit-tests/oscore-test/ut_oscore_task_test.c
In the osal_core_UT test, the test task was being deleted while it was in the midst of a UtPrintf call, which left the BSP mutex in a locked state, causing deadlock.
Using SEM_DELETE_SAFE attribute avoids task deletion for the mutex holder, and adding a small delay to the test case makes all the messages appear as expected (accounts for slow serial console on test platform).
Fixes #1088
Run osal_core_UT
Test now passes, does not deadlock
=> Fix #1088, avoid task delete during UtPrintf

docs/src/osalmain.dox, src/os/inc/osapi-network.h, src/os/inc/osapi-sockets.h
Fix #1096 - Doxygen group name update
CI, Doc only
None, updated doc
CI
None
None
=> Fix #1096, Add OSAL prefix to Network API group

src/tests/network-api-test/network-api-test.c
The number of asserts being printed was still taking longer than 1000ms on a 9600 baud serial link, so increasing the timeout allows tests to pass.
Fixes #1086
Run network-api-test
Test now passes
=> Fix #1086, increase timeout in network-api-test

src/os/inc/osapi-timebase.h, src/os/inc/osapi-timer.h, src/os/posix/build_options.cmake, src/os/rtems/build_options.cmake, src/os/vxworks/build_options.cmake, src/tests/time-base-api-test/time-base-api-test.c, src/unit-tests/ostimer-test/ut_ostimer_test.c
The underlying OS mechanism that rejects calls to timer APIs from timer callbacks does not work on anything except POSIX.  This skips these unit tests on non-POSIX platforms, and also adds documentation clearly indicating that the API must not be called from a timer context.
Fixes #1083
Run unit tests
Test now passes because this check is skipped on these platforms
QEMU / RTEMS 4.11
=> Fix #1083, timer reconfig tests

src/unit-tests/osfile-test/ut_osfile_fileio_test.c
Fix #1105 - individual parameter checks for `OS_rename`
None, unit test only
- Hardware: Intel i5/docker
None
None
=> Fix #1105, Add independent OS_rename functional test parameter checks

ut_assert/inc/utassert.h, ut_assert/inc/uttest.h, ut_assert/src/utassert.c, ut_assert/src/uttest.c
Migrates some of the assert extensions that were added for CFE coverage testing to the UtAssert level, so they can be used
in a wider scope of tests, not just CFE coverage.
The existing macros (e.g. UtAssert_INT32_EQ) are updated to use the same facility.
All macros are now also a single line and return the boolean pass/fail status, which was a useful feature of the CFE macros.
Fixes #1124 
Build and run all tests (functional + coverage) and confirm results are normal.
No operational change to existing asserts, but formatting of some logs may change a little bit, so it may affect some scripts that are looking for very specific message (although it did not affect any of my log parsing scripts).
**System(s) …
=> Fix #1124, add generic asserts from CFE coverage testing

src/tests/select-test/select-test.c, src/unit-tests/inc/ut_os_support.h, ut_assert/inc/utassert.h
Fixes #1118 Added UtAssert_MIR macro to avoid misuse of `UtAssertEx` when using the MIR case type `UTASSERT_CASETYPE_MIR`
1. Ran cFS Unit Tests
No changes expected. Macro UtAssert_MIR is now available for use.
Ubuntu 18.04 VM
Jose F. Martinez Pedraza / NASA GSFC
=> Fix #1118 Add UtAssert_MIR macro

src/ut-stubs/CMakeLists.txt
Adds the missing file to the library
Fixes #1120
Dependencies which invoke `OS_ShellOutputToFile` should now link successfully
Ubuntu
=> Fix #1120, add osapi-shell-stubs.c to OSAL stub library

.github/workflows/local_unit_test.yml
Check for absolute number of missed branches in GitHub workflow instead of checking a percentage branch coverage.
Ensure that the number of missed branches does not increase from the current 4 missed branches.
Fixes  #1115. The PR #1114 that is currently in the integration candidate branch has only 4 missed branches in the unit tests. This PR checks that the number of missed branches is <= 4 instead of checking the percentage branch coverage. This puts an absolute limit on the number of missed branches.
1. The local_unit_test workflow will currently fail on any branch that is not the current integration candidate, so I merged this PR into my fork's integration candidate branch to see it pass …
=> Fix #1115, Add absolute branch coverage check

ut_assert/inc/utassert.h, ut_assert/src/utassert.c, ut_assert/src/utbsp.c
Add two more test case variants, similar to NA, where failure of the test case does not translate to failure of the overall
test.
The additional cases have different levels of default visibility, and may be handled differently by the end user.  That is, some
tests may be skipped because they are truly NA (and nothing for the user to do to change that) and some tests may be skipped
because the system was not set up in a way that allowed them to be run (and the user must fix that and re-run).
Fixes #1130
Build and run all tests.  Also modify CFE test to use new casetype, confirm working as expected.
None
Ubuntu
Intended to differentiate between the nuances of all …
=> Fix #1130, add test case types similar to NA

.github/workflows/local_unit_test.yml
- Fix #1143 
Updates the regex to always get 4 matches (was ignoring .0%) so coverage enforcement will work as expected.  Also simplified the comparison.
Ran regex offline with various inputs including .0% case.
CI will work more consistently
- Hardware: Intel i5/Docker
None
None
=> Fix #1143, Regex update in coverage enforcement to match .0

src/os/shared/inc/os-shared-common.h
This function is documented as returning `void*`, and on some compilers this requires an explicit cast to `const char*` to avoid a warning.
Fixes #1141
None
Ubuntu
Isolated from draft contribution from @thesamprice in #1140
=> Fix #1141, add typecast to memchr call

src/tests/symbol-api-test/symbol-api-test.c
- Fix #1148 
Always runs symbol tests now and checks for not implemented.  Also will report MIR for a symbol table that won't fit instead of causing a failure.
Ran on MCP750, confirmed pass.  CI.
Symbol test now isn't skipped
- Hardware: MCP750
- OS: VxWorks 6.9
None
None
=> Fix #1148, Enable symbol api test and MIR dump too large

src/unit-tests/osloader-test/ut_osloader_symtable_test.c
- Fix #1151 
Makes either symbol too long or table to big error code returns into MIR, since it's not an actual failure of the test.
Ran on SP0 and CI
MIR for symbol table configuration related errors
- Hardware: SP0
- OS: VxWorks 6.9
None
None
=> Fix #1151, MIR symbol too long or table to long for osloader test

CMakeLists.txt, src/bsp/shared/inc/bsp-impl.h, src/bsp/shared/src/bsp_default_resourcecfg.c, src/os/inc/osapi-bsp.h, src/os/vxworks/src/os-impl-tasks.c, src/ut-stubs/osapi-bsp-stubs.c
Adds a simple BSP API to get/set integer flags for each resource type.  All bits are platform-defined, so this can be used to store any arbitrary platform flag.
Initial use case is for setting task flags on vxWorks platforms which require a certain task flag to be set.
Fixes #1154
Build and sanity check CFE, run all tests.
None on the framework build.  However this feature can be used internally to get around an issue where some vxWorks task flags need to be set only on one specific platform.
Ubuntu
=> Fix #1154, add bsp-specific configuration flag registry

src/os/portable/os-impl-bsd-sockets.c, src/os/shared/inc/os-shared-sockets.h, src/os/vxworks/CMakeLists.txt, src/os/vxworks/inc/os-impl-sockets.h, src/os/vxworks/src/os-impl-sockets.c, src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c, src/unit-test-coverage/ut-stubs/inc/OCS_ioLib.h, src/unit-test-coverage/ut-stubs/src/os-shared-sockets-impl-stubs.c, src/unit-test-coverage/vxworks/CMakeLists.txt, src/unit-test-coverage/vxworks/adaptors/CMakeLists.txt, src/unit-test-coverage/vxworks/adaptors/inc/ut-adaptor-sockets.h, src/unit-test-coverage/vxworks/adaptors/src/ut-adaptor-sockets.c, src/unit-test-coverage/vxworks/src/coveragetest-sockets.c, src/unit-test-coverage/vxworks/ut-stubs/CMakeLists.txt, src/unit-test-coverage/vxworks/ut-stubs/src/vxworks-os-impl-sockets-stubs.c
Adds the capability for the bsd sockets implementation to use a function provided by the OS layer to set the socket flags.
This allows VxWorks to have an alternative implementation that uses ioctl rather than fcntl to set the flags.
Fixes #1153
Build and sanity check CFE, run all tests
VxWorks will use `ioctl()` rather than `fcntl()` to set the socket flags
Ubuntu
=> Fix #1153, add os-specifc socket flag function

src/os/inc/common_types.h, src/os/inc/osapi-error.h
Minimal change to add a typedef for `osal_status_t`, a macro for constants/literals `OSAL_STATUS_C`, and an inline function to convert to "long" for printing/logging.
Partial/related to #1108 (this PR is just for the typedef and conversions, so that CFE/App code can potentially use the type)
Build and run CFE, run all tests
None
Ubuntu
This PR is only intended to avoid a chicken/egg scenario with the `osal_status_t` type.  That is, just to make it exist, so other entities can theoretically start using it, even if OSAL itself does not (yet).
=> Partial #1108, add typedef for OSAL status codes

src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c
Use a separate local variable rather than casting to (void **).
Fixes #1167 
Build with strict aliasing, confirm no warnings
None
Ubuntu
=> Fix #1167, vxWorks intLib stub aliasing issue

ut_assert/scripts/generate_stubs.pl
Removed 'extern' from function prototypes in stub generator script #1139.
=> Fix #1139, Remove extern in stub prototypes

.github/workflows/local_unit_test.yml
Fixes #1183 
https://github.com/ArielSAdamsNASA/osal/actions/runs/1372766073
Skip workflows on push for local unit tests if there is a duplicate workflow. 
=> Fix #1183, Add Duplicate Check to Local Unit Test

.github/workflows/codeql-cfe-build.yml, .github/workflows/codeql-osal-default.yml, .github/workflows/format-check.yml, .github/workflows/static-analysis.yml
Fixes #1188 
Tested on forked repos.
OSAL Static Analysis Reuse: https://github.com/ArielSAdamsNASA/osal/actions/runs/1391621678
cFS Static Analysis Reuse: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1391690020
OSAL CodeQL Reuse cFE Build: https://github.com/ArielSAdamsNASA/osal/runs/4023159610?check_suite_focus=true
OSAL CodeQL Reuse OSAL Default: https://github.com/ArielSAdamsNASA/osal/actions/runs/1390702434
cFS CodeQL Reuse: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1390777421
OSAL Format Check Reuse: https://github.com/ArielSAdamsNASA/osal/actions/runs/1390702433
cFS Format Check: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1390865379
cFS will hold …
=> Fix #1188, Reuse CodeQL, Static Analysis, Format Check

ut_assert/inc/utassert.h
- Fix #1200 by adding missing space to UtAssert_STUB_COUNT.
1. Built tests according to instructions in README Quick Start section.
2. Ran `./coverage-shared-task-testrunner | grep CallCount` in `build/unit-test-coverage/shared` to verify correct output.
Example output (old): "CallCountCFE_EVS_SendEvent() (0) == 0 (0)"  
Example output (new): "CallCount CFE_EVS_SendEvent() (0) == 0 (0)"
- Hardware: Lenovo ThinkPad t480s
- OS: Pop!_OS 21.10 64-bit
- Versions: N/A
N/A
N/A
Kurtis Dinelle (kurtisdinelle@gmail.com)
Student at Oregon State University
=> Fix #1200, Add missing space to UtAssert_STUB_COUNT

ut_assert/inc/utassert.h
- Fix #1196 
Adds UINT8 and UINT16 equivalents for UtAssert_UINT32_<Comparison> macros.
1. Built according to steps listed in README
2. Performed tests on each new macro with relevant input to ensure correctness (for example, passing 0 and 255 + 1 to UtAssert_UINT8_EQ and verifying that test passed).
Allows for users to call UtAssert comparisons on unsigned 8 and 16-bit values and provides expected wrap-around behavior without users needing to explicitly cast.
For example, `UtAssert_UINT8_EQ(0, 255 + 1)` outputs the following:  
Compare UINT8: 0 (0) == 255 + 1 (0)
- Hardware: ThinkPad t480s
- OS: Pop!_OS 21.10 64-bit
N/A
N/A
**Contributor …
=> Fix #1196, Add UINT8 and UINT16 equivalents for UtAssert_UINT32_<Comparison> macros

src/unit-test-coverage/portable/src/coveragetest-bsd-sockets.c, src/unit-test-coverage/shared/src/coveragetest-clock.c, src/unit-test-coverage/vxworks/src/coveragetest-tasks.c, src/unit-tests/oscore-test/ut_oscore_task_test.c
- Fix #1199
These new warnings are detected by the new compiler. They are all places in unit test where an uninitialized value is passed via "const" pointer into a unit under test.  By definition a "const" pointer is always an input.
While the warning is pedantically true - should not pass an uninitialized struct as an input - these were all unit tests where the object value is a don't-care value, so it does not matter.  But to fix the warning, simply need to initialize a value before making the call.
Fixes #1199
Build and run all tests on GCC 11.2 (Ubuntu 21.10)
None
Ubuntu 21.10
Joseph Hickey, Vantage …
=> Fix #1199, correct warnings on gcc11

src/ut-stubs/osapi-file-handlers.c
- Fix #1210 
- Provides consistent default OS_stat handler behavior
Tested with FM that relies on default behavior, CI
Avoids uninitialized variable risk in unit tests
- Hardware: i5/Docker
None
None
=> Fix #1210, Set output in OS_stat handler

src/os/inc/common_types.h, src/os/inc/osapi-idmap.h
Modifies the osal_id_t typedef to be a non-integer value.  The intent is to catch cases where it inappropriately being used as an integer value.
This is transparent so long as the osal_id_t typedef and provided check and conversion routines are used.
Fixes #1208 
Build and sanity check CFE and OSAL with and without OSAL_OMIT_DEPRECATED flag
When OSAL_OMIT_DEPRECATED is enabled (opt-in) this will catch misuse of OSAL IDs as integers, or failure to use correct `osal_id_t` typedef to hold the value.
Ubuntu 21.10
OSAL and CFE should all be compliant, but CFS apps probably are not yet compliant with this.  Hence why it is "opt-in" via OSAL_OMIT_DEPRECATED flag, like …
=> Fix #1208, typesafe definition of osal_id_t

src/os/shared/src/osapi-file.c, src/unit-test-coverage/shared/src/coveragetest-file.c, src/unit-test-coverage/shared/src/os-shared-coverage-support.c
Datagram sockets do not have a name_entry, it is set NULL.  If the user calls OS_FDGetInfo() on this type of ID, it will
pass the first test, so this needs to be checked for non-NULL.
Fixes #1222
Build and sanity check OSAL
Run all tests
Confirm coverage test is exercising the new check
Calling OS_FDGetInfo on a datagram socket returns an empty string in the Path field, it does not segfault.
Ubuntu
=> Fix #1222, protect if OS_FDGetInfo called on socket

src/unit-test-coverage/ut-stubs/CMakeLists.txt, src/unit-test-coverage/ut-stubs/src/os-shared-sockets-impl-handlers.c, src/unit-test-coverage/ut-stubs/src/os-shared-sockets-impl-stubs.c
- Fix #1214 
Built 32-bit and ran unit tests in valgrind, warnings squashed
No more uninit variable warnings
- Hardware: i5/wsl
None
None
=> Fix #1214, Resolve UT uninitialized variable warnings

docs/osal-detaildesign.doxyfile.in, src/os/portable/os-impl-bsd-select.c, ut_assert/inc/utassert.h, ut_assert/inc/utbsp.h, ut_assert/inc/utstubs.h, ut_assert/inc/uttest.h, ut_assert/src/utstubs.c
- Fix #1218 
Build detailed design, observe osal warnings go away.  Also built unit tests to confirm parameter name change worked.
Squash doxygen warnings
- Hardware: i5/wsl2
None
None
=> Fix #1218, Add ut_assert to doxygen and fix warnings

src/os/rtems/src/os-impl-loader.c
A clear and concise description of what the contribution is.
- Fixes #1220 
The ES "query application" command yields a telemetry packet that contains section information supplied by OS_ModuleGetInfo_Impl. Compared object section sizes (.text, .data, .bss) in the telemetry given by the query app command to section sizes reported by the "size" tool in the platform toolchain. Checked the disassembly of application objects built in FSW to find symbols in each section (.text, .data, .bss) and used the MM application to report the addresses for each. Verified that symbol addresses reported were contained in the interval [addr, addr + size) for each section. 
Tested with cFS bundle:
https://github.com/ezpollack/cFS/actions/workflows/build-cfs-r …
=> Fix #1220 Implement OS_ModuleGetInfo_Impl for RTEMS

.github/workflows/codeql-cfe-build.yml
Partial #1225 
changes tests input to boolean, changes source input for uses,
component-path to osal, changes to tests to test, removes makeprep input
github actions check: https://github.com/chillfig/osal/actions/runs/1993521933
Passing workflow
Ubuntu 18.4
Justin Figueroa, ASRC Federal
=> Partial #1225, Update cFS-build CodeQL reusable worfklow target

docs/osal-detaildesign.doxyfile.in, docs/src/CMakeLists.txt, docs/src/osal-apiguide.doxyfile.in, docs/src/osal-common.doxyfile.in
- Fix #1231
Built OSAL users guide locally and from bundle, no warnings.  Inspected generated documents
None, but osal-common.doxyfile can now be used by other documents to resolve OSAL references
- Hardware: i5/wsl
None
None
=> Fix #1231, Doxygen strip path and expose common config

src/os/portable/os-impl-no-select.c, src/os/rtems/CMakeLists.txt
- Fix #1248 
Implements os-impl-no-select.c for RTEMS or any other OS that has a configuration without select.
Currently only used for RTEMS when the network stack is disabled in the OSAL. On RTEMS the select call only works with network file descriptors.
In current RTEMS 4.11 and 5 builds, when the OSAL_CONFIG_INCLUDE_NETWORK option is false, the select call will still be included even though it cannot be used. The does not fail because the select call is still available in the RTEMS libraries.
If you build RTEMS 4.11 or 5 without the default network stack, the select call will not be included in the RTEMS libraries, causing the OSAL build to fail. In addition, RTEMS 6 removes the legacy network stack, so a …
=> FIX #1248, add os-impl-no-select.c for RTEMS

src/bsp/pc-rtems/build_options.cmake, src/bsp/pc-rtems/src/bsp_start.c, src/bsp/pc-rtems/src/pcrtems_bsp_internal.h, src/os/rtems/inc/os-rtems.h, src/os/rtems/src/os-impl-filesys.c, src/os/rtems/src/os-impl-loader.c
- Fix #1256
These changes add support for RTEMS 6 in the RTEMS OSAL and pc-rtems OSAL BSP. The changes consist of modifications to the conditional compilation blocks and a couple of new conditional compilation blocks in the pc-rtems OSAL BSP startup code to account for an include and API that was deprecated in RTEMS 6.
In the RTEMS OSAL, the existing conditional compilation blocks were flipped from:
```
if RTEMS 5
RTEMS 5 specific statement(s)
else
RTEMS 4.11 specific statement(s)
endif
```
to:
```
if RTEMS 4.11
RTEMS 4.11 specific statement(s)
else
RTEMS 5 and above specific statement(s)
endif
```
By flipping the blocks as described above, it should work with future versions of RTEMS provided the API does not …
=> Fix #1256, add rtems 6 support

src/unit-tests/osloader-test/CMakeLists.txt
Fixes #1150
Printed value of MOD variable in CMakeLists.txt to ensure that it gets set to one more than the OSAL_CONFIG_MAX_MODULES value
Ran OSAL unit tests
OSAL Loader unit tests will now support up to OSAL_CONFIG_MAX_MODULES modules.
- OS: RHEL 8.6
=> Fix #1150, Set OSAL Loader unit test number of modules to OSAL_CONFIG_MAX_MODULES.

ut_assert/src/uttools.c
Fixes  #1175 
GitHub Actions
Resolve TOCTOU bug by using fstat and fchmod instead of stat and chmod. 
=> Fix #1175, Use fstat and fchmod for TOCTOU Bug

src/tests/osal-core-test/osal-core-test.c, src/unit-tests/osloader-test/ut_module.c
**Checklist**
Fixes #1293
Removes all cases of redundant "return;" statements on the last line of void functions.
None, prior to submission.
No impact on behavior.
@thnkslprpt
=> Fix #1293, Remove 'return;' from last line of void functions.

ut_assert/src/uttools.c
File permissions in general are a POSIX concept, but this tool should be pure C99.  It should not rely on any POSIX headers or POSIX-specific API calls.
Fixes #1300
Build and run tests
No more build failures
Ubuntu 22.04
Setting permissions explicitly is not really necessary.
=> Fix #1300, do not set file permissions on UT assert outputs

src/os/rtems/src/os-impl-queues.c
Refactor rtems queue to not do size check, and to mimic posix logic.
Fixes #1279 
1. Build steps '...'
1. Execution steps '...'
- API Change: xxx (if applicable)
- Behavior Change: xxx (if applicable)
- Or no impact to behavior
- Hardware: [e.g. PC, SP0, MCP750]
- OS: [e.g. Ubuntu 18.04, RTEMS 4.11, VxWorks 6.9]
- Versions: [e.g. cFE 6.6, OSAL 4.2, PSP 1.3 for mcp750, any related apps or tools]
If included, …
=> Fix #1279, rtems queue multi-size, mimic posix logic

src/os/inc/osapi-clock.h, src/unit-test-coverage/shared/src/coveragetest-clock.c
Adds the following APIs which are direct reciprocals of the existing time conversion functions:
```
OS_time_t OS_TimeFromTotalSeconds(int64 tm)
OS_time_t OS_TimeFromTotalMilliseconds(int64 tm)
OS_time_t OS_TimeFromTotalMicroseconds(int64 tm)
OS_time_t OS_TimeFromTotalNanoseconds(int64 tm)
```
Fixes #1307
Added test cases to cover the new APIs
Build and run all tests to confirm that the new functions are working as intended
Adds reciprocal operations for existing time conversions
Ubuntu 22.04
=> Fix #1307, Add time conversion reciprocal functions

src/tests/condvar-test/condvar-test.c
The order of task wakeup when using OS_CondVarSignal() with multiple tasks pending may not be guaranteed.  This relaxes the test case so that a specific order is not assumed/required.  This also adjust certain sleep times to make sure the test waits long enough for the tasks to do the expected work.
Fixes #1318 
Execute the "condvar" test multiple times
Execute github workflows
Should resolve/avoid intermittent failure due to tasks not running in expected order
Ubuntu 22.04
As this failure was intermittent, this needs to be watched in the future to confirm there is no more failure
**Contributor Info - All …
=> Fix #1318, adjust timing on condvar tests

src/os/inc/osapi-macros.h, src/os/shared/src/osapi-printf.c
Adds a variant of the BUGCHECK macro that has no return value argument, which can be used in functions with no return value without the unusual syntax appearing in the code.
Fixes #1322
Basic build and run tests
Run cppcheck against source
Cppcheck does not report a syntax error
Ubuntu 22.04 (using cppcheck v2.7)
Just a wrapper macro is enough to satisfy cppcheck.  Added a note that the missing second argument (return value) is intentional on a void function.
=> Fix #1322, add BUGCHECK_VOID macro

.github/workflows/static-analysis.yml, CHANGELOG.md, CMakeLists.txt, src/os/inc/osapi-version.h, src/os/portable/os-impl-posix-dl-symtab.c, src/os/posix/src/os-impl-console.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/os/rtems/src/os-impl-filesys.c, src/os/rtems/src/os-impl-timebase.c, src/os/vxworks/src/os-impl-symtab.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c
- PR #1335. Addresses Issue #1270
- PR #1329. Addresses Issue #1328
- PR #1336. Addresses Issue #1324 and #1325
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/616/checks)
[osal Checks](https://github.com/nasa/osal/pull/1337/checks)
See PRs
Ubuntu 22.04
@jphickey
@dmknutsen
=> osal Integration candidate: Caelum-rc4+dev29

CMakeLists.txt
Move the UT stub library so it is not dependent on ENABLE_UNIT_TESTS
The "ut_osapi_stubs" library is mostly relevant for testing other applications, as opposed to testing OSAL itself.  Therefore this library should be provided regardless of whether OSAL is being tested.
Fixes #1328
Build and check OSAL in standalone build and CFE build
The `ut_osapi_stubs` library is always available
Ubuntu 22.04
=> Fix #1328, always provide UT stub library

src/os/vxworks/src/os-impl-symtab.c, src/unit-test-coverage/vxworks/src/coveragetest-symtab.c
* [x ] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x ] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.
Truncates symbol name in symbol table dump if the length exceeds OS_MAX_SYM_LEN.
Tested against VxWorks 6.9 
Dump completes successfully when symbol names exceed OS_MAX_SYM_LEN.
- Hardware: SP0
- OS: VxWorks 6.9
Dan …
=> Fix #1270: Truncate symbol name if > OS_MAX_SYM_LEN

.github/workflows/static-analysis.yml, src/os/portable/os-impl-posix-dl-symtab.c, src/os/posix/src/os-impl-console.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/os/rtems/src/os-impl-filesys.c, src/os/rtems/src/os-impl-timebase.c, src/unit-tests/oscore-test/ut_oscore_countsem_test.c
Passes a cmake configuration so cppcheck can use the exported commands, allowing it to use all header files that the actual build uses.
Also Resolves a number of other issues reported by cppcheck
Fixes #1324
Fixes #1325
Build and run tests
Verify results of static analysis workflow
Static analysis workflow should be clean
Github workflow
=> Fix #1324, Fix #1325, cppcheck updates 

.github/workflows/build-osal-documentation.yml, .github/workflows/local_unit_test.yml, CHANGELOG.md, docs/src/CMakeLists.txt, src/os/inc/osapi-version.h, src/os/portable/os-impl-bsd-sockets.c
- PR #1342. Addresses Issue #1340
- PR #1341. Addresses Issue #1339
- PR #1321. Addresses Issue #1262
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/629/checks)
[osal Checks](https://github.com/nasa/osal/pull/1343/checks)
See PRs
Ubuntu 20.04
@jphickey
@thnkslprpt
=> osal Integration candidate: Caelum-rc4+dev31

.github/workflows/build-osal-documentation.yml, docs/src/CMakeLists.txt
When building as part of CFE/CFS, register the osal header list file (osal-public-api.doxyfile) as a dependency of the doc-prebuild abstract target.  This way, CFE and any other CFS apps that refer to the OSAL headers in their documentation can easily ensure that this (and any other file produced by other modules) exist prior to attempting to run doxygen.
Fixes #1339
Build documentation
None directly to OSAL, but dependent items can now operate correctly
Github hosted runner
=> Fix #1339, add doc-prebuild dependency

.github/workflows/build-osal-documentation.yml, .github/workflows/local_unit_test.yml
Use the "v3" version of checkout and upload-artifact actions, which resolves a warning about depending on an obsolete node.js version.
Fixes #1340 
Execute workflow
No more warning about node.js 12
Github hosted runner
=> Fix #1340, Update action versions

default_config.cmake, osconfig.h.in, src/os/shared/src/osapi-task.c
- Fix #1345 
CI, also tested on RTEMS5/leon3 with OS_FP_ENABLED
No default change but supports adding flags at task creation
CI
None
None
=> Fix #1345, Support adding default flags at task creation

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/posix/src/os-impl-filesys.c
- PR #1355. Addresses Issue #1173
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/647/checks)
[osal Checks](https://github.com/nasa/osal/pull/1358/checks)
See PRs
Ubuntu 20.04
@jphickey
=> osal Integration candidate: Caelum-rc4+dev37

src/os/posix/src/os-impl-filesys.c
Generating the system_mountpt string via a single call to snprintf triggered a compiler warning about overlapping memory.  However this does not seem like a real warning, as the volume_name should always be null terminated before the overlap would be possible.
By separating this to be a separate append of the volume_name along with an explicit size check to ensure the buffers indeed do not overlap, this avoids the warning.
Fixes #1173
Build and run all tests
Avoids a false compiler warning about possible pointer overlap by explicitly checking and limiting the string length being appended.
No functional change, as the generated "system_mountpt" string should be …
=> Fix #1173, separate append on volume_name to system_mountpt

CHANGELOG.md, src/os/inc/osapi-version.h, ut_assert/inc/utgenstub.h, ut_assert/inc/utstubs.h, ut_assert/src/utstubs.c
- PR #1352. Addresses Issue #1344
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/TBD/checks)
[osal Checks](https://github.com/nasa/osal/pull/TBD/checks)
See PRs
Ubuntu 20.04
@jphickey
=> osal Integration candidate: Caelum-rc4+dev38

ut_assert/inc/utgenstub.h, ut_assert/inc/utstubs.h, ut_assert/src/utstubs.c
Improves default support for return values of sizes other than 32 bits. Previously this required a custom handler for any value that was not a 32 bit integer.  With this update any integer value can be used, and a value translation will occur if the size is different.  Thus boolean values, 8,16, and 64-bit ints can be configured through the same basic API without needing to add a handler.
Fixes #1344
Build and run all tests, including CFS app tests, to confirm all still run as expected.
No change to _existing_ behavior - all currently-implemented test cases should continue to behave as they have in the past, whether they used a 32-bit integer return or if they …
=> Fix #1344, UT assert stub return values

ut_assert/inc/utstubs.h
Adds a function and parameter description for this API which resolves a doxygen warning about it being undocumented.
Fixes #1361
Build full set of documentation
Functions are fully documented
Debian
=> Fix #1361, add doxygen for UT_ConfigureGenericStubReturnValue

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/rtems/src/os-impl-timebase.c
- PR #1367. Addresses Issue #1366
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/653/checks)
[osal Checks](https://github.com/nasa/osal/pull/1369/checks)
See PRs
Ubuntu 20.04
@pepepr08
=> osal Integration candidate: Caelum-rc4+dev39

src/os/rtems/src/os-impl-timebase.c
Fix #1366
- Hardware: GR740
- OS: RTEMS
- Versions: cFS draco-rc2 + mods
Jose F. Martinez Pedraza | GSFC 582
=> Fix #1366, removed cast that hid bug at compile time

src/os/inc/osapi-clock.h, src/os/inc/osapi-file.h, src/os/inc/osapi-idmap.h, src/os/inc/osapi-macros.h, src/os/inc/osapi-select.h
Correct a few syntactical items that are valid C99 but not valid for C++03.  This includes use of the designated initializer, compound literals, variadic macros, and a trailing comma in enum declarations.
Note this only matters for public API headers, as some users may need to include these directly from a c++ file.  For normal C source files, these are all compiled as C99 and thus the syntax is fine.
Fixes #1365
Build and run all OSAL tests
No impact to behavior, headers are now valid syntax for C++03 (and C99, of course)
Debian (using g++ 12.2 to check C++ syntax)
**Contributor Info - All information REQUIRED for consideration of pull …
=> Fix #1365, fixup API headers for C++

CHANGELOG.md, src/os/inc/osapi-version.h, ut_assert/src/utassert.c
- PR #1393. Addresses Issue #1392
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/677/checks)
[osal Checks](https://github.com/nasa/osal/pull/1395/checks)
See PRs
Ubuntu 20.04
@dmknutsen
=> osal Integration candidate: Caelum-rc4+dev52

ut_assert/src/utassert.c
Replace these with long and unsigned long, respectively, as some old systems might not have these types even if it does provide stdint.h
Fixes #1396
Build on vxworks 6.9 (gcc 4.3.3)
Build should succeed
GSFC VxWorks build host
=> Fix #1396, do not use intmax_t/uintmax_t types

src/tests/condvar-test/condvar-test.c
This reports that the functionality is not implemented and reports it as an MIR result, instead of having most/all of the tests fail.
Fixes #1404
Build with "no-condvar" implementation and run tests
Confirm that the tests now succeed with a single MIR output, rather than reporting many failures.
Debian
=> Fix #1404, skip condvar tests if not implemented

src/os/rtems/src/os-impl-tasks.c
- Fix #1281 
Ran on RTEMS 5.  Sample output:
```
-------------------------------------------------------------------------------
CPU USAGE BY THREAD
------------+----------------------------------------+---------------+---------
ID         | NAME                                   | SECONDS       | PERCENT
------------+----------------------------------------+---------------+---------
0x09010001 | IDLE                                   |      6.924443 |  86.332
0x0a010001 | UI1                                    |      0.000000 |   0.000
0x0a010002 | ntwk                                   |      0.002736 |   0.034
0x0a010003 | ETH0                                   |      0.000000 |   0.000 …
```
=> Fix #1281, Set RTEMS task name for cpuuse

src/os/rtems/src/os-impl-binsem.c, src/os/rtems/src/os-impl-countsem.c
- Fix #1406 
Ran on RTEMS 5 w/ CF semaphore flow control using counting semaphore and it worked.
- Squashes bug, sem take with no timeout works
- Hardware: leon3 QEMU
- OS: RTEMS 5
- Versions: basically main w/ local RTEMS mods
Opened separate issue to add functional test that covers both counting and binary semaphores
- #1411
None
=> Fix #1406, Squash RTEMS sem take timeout bug

src/os/rtems/src/os-impl-console.c, src/os/rtems/src/os-impl-timebase.c
- Fix #1421 
CI and RTEMS in gr712 QEMU
Output:
```
-------------------------------------------------------------------------------
CPU USAGE BY THREAD
------------+----------------------------------------+---------------+---------
ID         | NAME                                   | SECONDS       | PERCENT
------------+----------------------------------------+---------------+---------
0x09010001 | IDLE                                   |     19.496490 |  70.025
0x0a010001 | UI1                                    |      0.624546 |   2.243
0x0a010002 | ntwk                                   |      0.008347 |   0.029
0x0a010003 | ETH0                                   |      0.000051 | …
```
=> Fix #1421, Add RTEMS console and timebase posix task names

src/unit-test-coverage/ut-stubs/src/libc-stdlib-stubs.c
A clear and concise description of what the contribution is.
- Fix #1412
- This corrects the memory alignment calculation as already described in the issue.
- I rebuild and tested this fix with exactly the cFS/OSAL code, configuration and environment in which bug caused a crash of the test `coverage-vxworks-tasks-testrunner.exe`. The test executed successfully (with out crash) when build with `-O2` as well as `-O0`. This was  RTEMS 6, ARM architecture and BSP `xilinx_zynq_a9_qemu` and tests run on QEMU.
- Moreover, I build and run the current cFS (with OSAL) git head with and without this patch and did run all tests. cFS: …
=> Fix #1412, Wrong memory alignment calculation

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/posix/src/os-impl-tasks.c
- PR #1430. Addresses Issue #1429
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/723/checks)
[osal Checks](https://github.com/nasa/osal/pull/1434/checks)
See PRs
Ubuntu 20.04
@jphickey
=> osal Integration candidate: Caelum-rc4+dev66

src/os/posix/src/os-impl-tasks.c
The glibc pthread implementation puts additional data structures at the base of the stack.  The size of these is not known, but the only thing to go by is PTHREAD_MIN_STACK -- which should always be enough to hold the required objects.
Instead of simply assuring that the stack is at least PTHREAD_MIN_STACK, add this to the requested stack instead.  This in turn will ensure that the user always has at least their requested stack size available for actual use.
If the pthread implementation does not advertise a PTHREAD_MIN_STACK value, then just reserve 1 extra page.
Fixes #1429
Execute all tests, execute CFE
Internal stack size is now larger than requested in the …
=> Fix #1429, adjust pthread stack to account for TCB+TLS

src/os/rtems/inc/os-rtems.h
Ignore the call to pthread_setname_np() on RTEMS 4.x.  This becomes a no-op, and OSAL is able to build again.
Fixes #1441
Build on RTEMS 4.11
Build succeeds
Debian with RTEMS 4.11 toolchain
=> Fix #1441, patch build for old RTEMS

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/shared/src/osapi-errors.c
- PR #1436. Addresses Issue #1435
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/TBD/checks)
[osal Checks](https://github.com/nasa/osal/pull/TBD/checks)
See PRs
Ubuntu 20.04
@ahatstat
=> osal Integration candidate: Equuleus-rc1+dev2

src/os/shared/src/osapi-errors.c
Fixes #1435
Build and run all coverage tests including coverage-shared-errors-testrunner on ARM/Linux and PC/Ubunutu.  All tests pass and do not seg fault.
Fewer seg faults when running unit tests
ARM9/Embedded Linux
PC/Ubuntu 22.04LTS
N/A
N/A
Andrew Hatstat, Geost
=> Fix pointer error in OS_GetErrorName

.github/workflows/standalone-build.yml, src/os/shared/src/osapi-filesys.c
**Checklist**
- Fixes #1107
- Superfluous `if` condition removed - removing an unreachable branch (condition is always `true`) and slightly improving test coverage.
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.
No change to behavior.
Avi Weiss @thnkslprpt
=> Fix #1107, Remove unreachable branch (superfluous if condition)

src/tests/time-base-api-test/time-base-api-test.c, src/unit-test-coverage/shared/src/coveragetest-idmap.c
**Checklist**
- Fixes #1330
- A couple stray variables that were declared mid-function were moved to the top of their respective functions.
GitHub CI actions all passing successfully (excl. cppcheck issues being addressed in https://github.com/nasa/osal/issues/1325)
All variables declared top of function as per cFS conventions/guidelines.
Avi Weiss @thnkslprpt
=> Fix #1330, Move variables declared mid-function to the top

src/unit-tests/osfile-test/ut_osfile_test.c
**Checklist**
- Fixes #1356 
- 2 uses of `goto` are replaced with simple return statements.
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.
No change to logic.
Program flow is clearer, and removes the only remaining use of `goto` in OSAL.
Avi Weiss @thnkslprpt
=> Fix #1356, Remove stray remaining 'goto' in OSAL test code

src/os/rtems/src/os-impl-filesys.c, src/os/shared/src/osapi-filesys.c, src/os/vxworks/src/os-impl-filesys.c, src/tests/file-sys-add-fixed-map-api-test/file-sys-add-fixed-map-api-test.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/vxworks/src/coveragetest-filesys.c
Use the "virtual_path" instead of "device_name" as the name record for FS_BASED entries.  This should allow duplicate detection to work as expected.
The device_name on mappings made via this method will now be an empty string.  It is not relevant because this type of map is used for devices that are already mounted.
Fixes #1433
Run all tests, validate OSAL behavior 
Using `OS_FileSysAddFixedMap()` with similar system paths should work as expected.
Debian
Duplicate detection is now done on virtual path, not system path.  Therefore it is (theoretically) possible to mount the same system path in more than one virtual …
=> Fix #1433, use virtual path as name for FS_BASED maps

CHANGELOG.md, src/examples/tasking-example/tasking-example.c, src/os/inc/osapi-version.h, src/os/posix/inc/os-impl-tasks.h, src/os/posix/src/os-impl-console.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/tests/bin-sem-test/bin-sem-test.c, src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c, src/tests/count-sem-test/count-sem-test.c, src/tests/osal-core-test/osal-core-test.c, src/tests/osal-core-test/osal-core-test.h, src/tests/queue-test/queue-test.c
- PR #1450. Addresses Issue #1449
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/747/checks)
[osal Checks](https://github.com/nasa/osal/pull/1453/checks)
See PRs
Ubuntu 20.04
@jphickey
=> osal Integration candidate: Equuleus-rc1+dev6

src/examples/tasking-example/tasking-example.c, src/os/posix/inc/os-impl-tasks.h, src/os/posix/src/os-impl-console.c, src/os/posix/src/os-impl-tasks.c, src/os/posix/src/os-impl-timebase.c, src/tests/bin-sem-test/bin-sem-test.c, src/tests/bin-sem-timeout-test/bin-sem-timeout-test.c, src/tests/count-sem-test/count-sem-test.c, src/tests/osal-core-test/osal-core-test.c, src/tests/osal-core-test/osal-core-test.h, src/tests/queue-test/queue-test.c
When the OS_TaskCreate() function is called with a non-NULL stack pointer, the POSIX implementation now should use this pointer as intended.  Previously it was always allocating a new stack buffer, ignoring the passed-in pointer.
NOTE: When using this feature, the caller must use caution to make sure the buffer being passed in is large enough to use as a task stack.  Particularly when running under a desktop Linux/Glibc environment, the infrastructure puts a considerably large object on the stack.  For example, in the osal-core-tests, the stack size was too small.
Fixes #1449
Build and run all tests.  Added tests that ensure the stack pointer is being honored as expected.
**Expected behavior …
=> Fix #1449, POSIX implementation honors stack pointer

src/bsp/generic-rtems/CMakeLists.txt, src/bsp/generic-rtems/config/default_bsp_rtems_cfg.h, src/bsp/generic-rtems/src/bsp_cmdline.c, src/bsp/generic-rtems/src/bsp_cmdline.h, src/bsp/generic-rtems/src/bsp_console.c, src/bsp/generic-rtems/src/bsp_init.c, src/bsp/generic-rtems/src/bsp_mount_setupfs.c, src/bsp/generic-rtems/src/bsp_no_cmdline.c, src/bsp/generic-rtems/src/bsp_no_shell.c, src/bsp/generic-rtems/src/bsp_setupfs.h, src/bsp/generic-rtems/src/bsp_shell.c, src/bsp/generic-rtems/src/bsp_shell.h, src/bsp/generic-rtems/src/bsp_start.c, src/bsp/generic-rtems/src/bsp_start.h, src/bsp/generic-rtems/src/bsp_tarfs_setupfs.c, src/bsp/generic-rtems/src/pcrtems_bsp_internal.h
- Fix #1349 
- Fix #1447
Splits up bsp_start.c so features can be optionally included: cmdline, shell, stand alone exe vs module
RTEMS configuration is now in bsp_init.c, included based on stand alone/module selection
Ran w/ LEON3 QEMU with/without shell and stand alone/module options.
PC behavior shouldn't change based on default options matching previous behavior
Except for the file system and command line, the rest is usable by LEON3
LEON3 QEMU modified as documented by RCC:
```
apt-get update && apt-get install -y ninja-build pkg-config libglib2.0-dev python3 python3-pip python3-setuptools python3-wheel libpixman-1-dev && pip3 install …
```
=> Fix #1349 #1447, Break up pc-rtems to support generic configuration and add tarfs support

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/shared/src/osapi-idmap.c, src/os/vxworks/src/os-impl-console.c
- PR #1467. Addresses Issue #1466
- PR #1470. Addresses Issue #1469
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/783/checks)
[osal Checks](https://github.com/nasa/osal/pull/1471/checks)
See PRs
Ubuntu 20.04
@avan989
=> osal Integration candidate: Equuleus-rc1+dev14

.github/workflows/standalone-build.yml, CHANGELOG.md, src/os/inc/osapi-version.h
- PR #1419. Addresses Issue #1417 and #1418
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/788/checks)
[osal Checks](https://github.com/nasa/osal/pull/1476/checks)
See PRs
Ubuntu 20.04
@thnkslprpt
=> osal Integration candidate: Equuleus-rc1+dev16

.github/pull_request_template.md, CHANGELOG.md, src/bsp/shared/inc/bsp-impl.h, src/bsp/shared/src/bsp_default_resourcecfg.c, src/os/inc/osapi-version.h, src/os/rtems/CMakeLists.txt, src/os/vxworks/inc/os-impl-dirs.h, ut_assert/src/utstubs.c
- PR #1416. Addresses Issue #1415
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/807/checks)
[osal Checks](https://github.com/nasa/osal/pull/1481/checks)
See PRs
Ubuntu 20.04
@thnkslprpt
=> osal Integration candidate: Equuleus-rc1+dev20

src/os/shared/src/osapi-filesys.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/ut-stubs/inc/OCS_string.h, src/unit-test-coverage/ut-stubs/override_inc/string.h, src/unit-test-coverage/ut-stubs/src/libc-string-stubs.c
Fixes #1485 - Adding a check using strstr() to make sure the user-inputted file paths don't contain ".." to prevent writing files outside the virtual mount point
Built and ran all tests
Will block paths with ".."
OS: RHEL 8.10
Tvisha Andharia - GSFC 582 intern
=> Adding a strstr() check

src/unit-tests/oscore-test/ut_oscore_test.c
Fix #1498, update ut_oscore_test.c to run OS_TaskFindIdBySystemData only once
* [ x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [ x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.
A clear and concise description of what the contribution is.
Fix #1498, update ut_oscore_test.c to run OS_TaskFindIdBySystemData only once
```
[BEGIN] 43 OS_TaskFindIdBySystemData
[ PASS] 43.001 ut_oscore_task_test.c:621 - OS_TaskFindIdBySystemData(NULL, &sysdata, sizeof(sysdata)) (-2) == …
```
=> Fix #1498, update ut_oscore_test.c

.github/workflows/build-osal-documentation.yml, .github/workflows/standalone-build.yml, src/unit-tests/ostimer-test/ut_ostimer_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.h, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
- Fixes #1503  The timer test logic was relying on undefined/non-guaranteed behavior.
- Also updated the start time used for timers to improve accuracy and make test pass on slower/less accurate systems.
- Updated workflow to do an apt update before the apt install
1. Build and run tests
- Test now passes on RTEMS / LEON3
- RTEMS 5 / LEON3
If included, identify any third party code and provide text file of …
=> Fix #1503, Update timer interval comparison

CHANGELOG.md, src/os/inc/osapi-version.h, src/unit-test-coverage/ut-stubs/src/libc-stdlib-stubs.c
- PR #1497. Addresses Issue #1496
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/836/checks)
[osal Checks](https://github.com/nasa/osal/pull/1505/checks)
See PRs
Ubuntu 20.04
@pepepr08
=> osal Integration candidate: Equuleus-rc1+dev28

.github/workflows/build-osal-documentation.yml, .github/workflows/standalone-build.yml
Fixes nasa/cFS#839
GitHub Actions. For example, https://github.com/arielswalker/cFS/actions/runs/14499022671.
Workflows will not longer throw error `This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101`
GitHub Actions
**Additional Context**
Ariel Walker, MCSG TECH.
=> Fix nasa/cFS#839, Update Workflows to Ubuntu 22.04

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/posix/src/os-impl-tasks.c, src/tests/bin-sem-test/bin-sem-test.c, src/tests/count-sem-test/count-sem-test.c, ut_assert/inc/utstubs.h
- PR #1509. Addresses Issue #1445
- PR #1508. Addresses Issues #1484
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/857/checks)
[osal Checks](https://github.com/nasa/osal/pull/1512/checks)
See PRs
Ubuntu 20.04
@AlSharji0
@jphickey
=> osal Integration candidate: Equuleus-rc1+dev31
