nasa/osal

.gitignore
Just adding gitignore rules to prevent the dirty git status when project is built:
```
#
#	build/inc/
```
=> Added missing gitignore rules

.travis.yml
Adding travis.yml file for cppcheck on flight code. src/bsp and src/os
=> issue #314, adding cppcheck to bsp and os

ut_assert/inc/utassert.h
Fix #598 - typo fix
CI - comment change only
None
N/A
None
None
=> Fix #598, Correct UtAssert_ZERO description typo

.github/workflows/static-analysis.yml
Fix #740
See action runs in fork
Static analysis workflow runs on pull requests and push.
Workflow saves log file as an artifact for analysis.
n/a
n/a
n/a
=> Fix #740, Re-add automated static code analysis 

src/os/inc/osapi-common.h, src/unit-tests/oscore-test/ut_oscore_misc_test.c, src/unit-tests/oscore-test/ut_oscore_misc_test.h, src/unit-tests/oscore-test/ut_oscore_test.c
Ensures correlation between the unit-tests and documented return values for the OSAL common API.
Fixes #1010 
Ubuntu
=> Fix #1010, resolve discrepancies between common API and unit tests

src/os/inc/osapi-dir.h, src/unit-tests/osfile-test/ut_osfile_dirio_test.c
Ensures correlation between the unit-tests and documented return values for the OSAL directory API.
Fixes #1012 
Ubuntu
=> Fix #1012, resolve discrepancies between dir API and unit tests

src/os/portable/os-impl-posix-gettime.c
- Fix #1177 
- rename comments from OS_XXXTime to OS_XXXLocalTime
No code changed.
- Or no impact to behavior
None
Full name and company/organization/center of all contributors ("Personal" if individual work)
- If NASA Civil Servant Employee or GSFC Contractor on SES II
- Address/email/phone and …
=> Fix #1177 Rename OS_XXXTime to OS_XXXLocalTime in comments.

src/os/inc/osapi-version.h
Per conversation in CCB:2022-03-24 and in https://github.com/nasa/cFE/commit/e5be0612ad6bf9db09ddf640306a65292abce2d5#commitcomment-69358417
Ensuring REVISION number is set to 99 and MISSION_REV = 0xFF
Text and documentation only
No behavior change
n/a
https://github.com/nasa/cFE/commit/e5be0612ad6bf9db09ddf640306a65292abce2d5#commitcomment-69358417
none
Gerardo E. Cruz-Ortiz, NASA
=> HOTFIX #1233, Revert changes to versioning information

.github/workflows/codeql-cfe-build.yml, .github/workflows/codeql-osal-default.yml
- Fix #1225 
CI
None, just fixes codeql workflows
CI
None
None
=> Fix #1225, Update codeql workflows for reusable update

CMakeLists.txt
- Fix #1263 
This updates the main minimum required version from 2.8.12 to 3.5
CI
None, just updates minimum required version
CI
- #1264
None
=> Fix #1263, Update minimum required cmake version

src/os/vxworks/inc/os-impl-tasks.h
- Fix #1271
CI
Resolves bug, otherwise no change in behavior
CI, will try to coordinate testing the fix on a real VxWorks 7, 32-bit platform
None
None
=> Fix #1271, Ensure address alignment of TCB for VxWorks 7

src/unit-tests/osfile-test/ut_osfile_test.c
- Fix #1273
CI
None
CI
None
None
=> Fix #1273, Remove stray terminators

CHANGELOG.md, src/os/inc/osapi-macros.h, src/os/inc/osapi-version.h, src/os/shared/src/osapi-printf.c
- PR #1323. Addresses Issue #1322
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/613/checks)
[osal Checks](https://github.com/nasa/osal/pull/1332/checks)
See PRs
Ubuntu 20.04
@jphickey
=> osal Integration candidate: Caelum-rc4+dev28

.github/workflows/build-osal-documentation.yml, .github/workflows/local_unit_test.yml, CHANGELOG.md, src/os/inc/osapi-version.h
- PR #1334. Addresses Issue #1333
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/620/checks)
[osal Checks](https://github.com/nasa/osal/pull/1338/checks)
See PRs
Ubuntu 22.04
@skliper
=> osal Integration candidate: Caelum-rc4+dev30

.github/workflows/build-osal-documentation.yml, .github/workflows/local_unit_test.yml
- Fix #1333
CI
Just updates CI to use Ubuntu 20.04
CI
None
None
=> Fix #1333, Update CI to use Ubuntu 20.04

src/os/portable/os-impl-bsd-sockets.c
**Checklist**
Fixes #1262
Updates incorrect function purpose in function header comment.
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.
None. Comments change only.
Avi Weiss @thnkslprpt
=> Fix #1262, Update incorrect function header comment

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/shared/src/osapi-idmap.c
- PR #1327. Addresses Issue #1110
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/654/checks)
[osal Checks](https://github.com/nasa/osal/pull/1373/checks)
See PRs
Ubuntu 20.04
@thnkslprpt
=> osal Integration candidate: Caelum-rc4+dev40

src/os/shared/src/osapi-idmap.c
**Checklist**
Fixes #1110 
Changes 2 mutually exclusive, consecutive `if` statements to an `if`/`else` block.
I believe this is the most parsimonious fix to this issue.
GitHub CI Unit Tests all passing successfully.
No change to behavior.
Avi @thnkslprpt
=> Fix #1110, Modify unreachable branch in OS_ObjectIdAllocateNew

.github/workflows/icbundle.yml, CHANGELOG.md, src/os/inc/osapi-version.h
- PR #1383. Addresses Issue #1382
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/669/checks)
[osal Checks](https://github.com/nasa/osal/pull/1384/checks)
See PRs
Ubuntu 20.04
@dzbaker
=> osal Integration candidate: Caelum-rc4+dev47

.github/workflows/icbundle.yml
A clear and concise description of what the contribution is.
- Addresses issue #1382.
Generated IC branch in fork.
Adds new workflow for integration candidate branch generation.
Dylan Z. Baker/NASA GSFC 582
=> Fix #1382, Create Workflow for IC Bundle Generation

ut_assert/src/utassert.c
* [x ] I reviewed the [Contributing Guide](https://github.com/nasa/cFE/blob/main/CONTRIBUTING.md).
* [x ] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.
Adds additional counters to test summary.
Fixes #1392 
Executed functional tests and confirmed output is as expected.
Dan Knutsen
NASA Goddard
=> Fix #1392, Add additional counters to test summary

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/rtems/src/os-impl-binsem.c, src/os/rtems/src/os-impl-countsem.c, src/os/rtems/src/os-impl-tasks.c
- PR #1407. Addresses Issue #1281
- PR #1408. Addresses Issue #1406
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/704/checks)
[osal Checks](https://github.com/nasa/osal/pull/1414/checks)
See PRs
Ubuntu 20.04
@skliper
=> osal Integration candidate: Caelum-rc4+dev58

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/rtems/src/os-impl-console.c, src/os/rtems/src/os-impl-timebase.c
- PR #1422. Addresses Issue #1421
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/711/checks)
[osal Checks](https://github.com/nasa/osal/pull/1425/checks)
See PRs
Ubuntu 20.04
@skliper
=> osal Integration candidate: Caelum-rc4+dev60

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/rtems/inc/os-rtems.h, src/os/shared/src/osapi-version.c
- PR #1437. Addresses Issue #1420
- PR #1442. Addresses Issue #1441
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/731/checks)
[osal Checks](https://github.com/nasa/osal/pull/1443/checks)
See PRs
Ubuntu 20.04
@jphickey
@dzbaker
=> osal Integration candidate: Equuleus-rc1+dev1

.github/workflows/standalone-build.yml, CHANGELOG.md, src/os/inc/osapi-version.h, src/os/shared/src/osapi-filesys.c
- PR #1368. Addresses Issue #1107
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/TBD/checks)
[osal Checks](https://github.com/nasa/osal/pull/TBD/checks)
See PRs
Ubuntu 20.04
@thnkslprpt
=> osal Integration candidate: Equuleus-rc1+dev3

.github/workflows/build-osal-documentation.yml, .github/workflows/icbundle.yml, .github/workflows/standalone-build.yml, CHANGELOG.md, src/os/inc/osapi-version.h
- PR #1460. Addresses Issue #1549
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/763/checks)
[osal Checks](https://github.com/nasa/osal/pull/1461/checks)
See PRs
Ubuntu 20.04
@chillfig
=> osal Integration candidate: Equuleus-rc1+dev12

CHANGELOG.md, src/os/inc/osapi-version.h, src/os/shared/src/osapi-filesys.c, src/unit-test-coverage/shared/src/coveragetest-filesys.c, src/unit-test-coverage/ut-stubs/inc/OCS_string.h, src/unit-test-coverage/ut-stubs/override_inc/string.h, src/unit-test-coverage/ut-stubs/src/libc-string-stubs.c
- PR #1486. Addresses Issue #1485
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/810/checks)
[osal Checks](https://github.com/nasa/osal/pull/1487/checks)
See PRs
Ubuntu 20.04
@tandharia
=> osal Integration candidate: Equuleus-rc1+dev21

.github/workflows/build-osal-documentation.yml, .github/workflows/standalone-build.yml, CHANGELOG.md, src/os/inc/osapi-version.h, src/os/portable/os-impl-no-select.c, src/tests/osal-core-test/osal-core-test.c, src/tests/osal-core-test/osal-core-test.h, src/unit-test-coverage/portable/src/coveragetest-bsd-select.c, src/unit-tests/oscore-test/ut_oscore_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.c, src/unit-tests/ostimer-test/ut_ostimer_test.h, src/unit-tests/ostimer-test/ut_ostimer_timerio_test.c
- PR #1495. Addresses Issue #1472
- PR #1499. Addresses Issue #1498
- PR #1504. Addresses Issue #1503
- PR #1502. Addresses Issue #1501
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/831/checks)
[osal Checks](https://github.com/nasa/osal/pull/1500/checks)
See PRs
Ubuntu 20.04
@pepepr08
@avan989
=> osal Integration candidate: Equuleus-rc1+dev27

src/tests/osal-core-test/osal-core-test.c, src/tests/osal-core-test/osal-core-test.h
Fixes #1501 
Build and run test on linux and RTEMS / LEON3
-  RTEMS / LEON3
Jose F. Martinez Pedraza
=> Fix #1501, Update stack sizes for test tasks

src/os/portable/os-impl-no-select.c, src/unit-test-coverage/portable/src/coveragetest-bsd-select.c
Part #1472. This only includes the code changes. In the issue I think it also suggests to include verification in workflows, which is not included here.
1. Built and tested on NASA internal rtems project
No build failures when building osal without network for rtems
- Ubuntu22 server building for RTEMS/SPARC
Jose F Martinez Pedraza / NASA 582
=> Part #1472, Update Select functions params

src/unit-test-coverage/ut-stubs/src/libc-stdlib-stubs.c
Fixes #1496 
1. make SIMULATION=native ENABLE_UNIT_TESTS=true prep
2. make install
3. make test
- All tests pass
OS: Docker Ubuntu22/arm64 on Mac M3 Pro
Jose F Martinez Pedraza / NASA GSFC 582
=> Fix #1496, Update malloc stub

.github/workflows/build-osal-documentation.yml, .github/workflows/standalone-build.yml, CHANGELOG.md, src/os/inc/osapi-version.h
- PR #1506. Addresses Issue nasa/cFS#839
[cFS Bundle Checks](https://github.com/nasa/cFS/pull/843/checks)
[osal Checks](https://github.com/nasa/osal/pull/1507/checks)
See PRs
Ubuntu 20.04
@arielswalker
=> osal Integration candidate: Equuleus-rc1+dev29
